-- The output have been generated with the assistance of Claude at 2026-06-16T10:00:00Z UTC. The content has been verified by the designated engineer.

{{
  config(
    materialized         = 'incremental',
    unique_key           = 'SURROGATE_KEY',
    incremental_strategy = 'merge',
    on_schema_change     = 'fail',
    tags                 = ['silver', 'staging', 'netsuite']
  )
}}

{#
  Model   : stg_ns_item
  Layer   : staging
  Grain   : 1 row per STG_NS_ITEM
  Schema  : static (explicit column list from Silver LLD)
  Cleaning: inline (TransformationRule expressions from Silver LLD)
  Source  : {{ source('ns', 'ITEM') }}
  Watermark: LASTMODIFIEDDATE
#}

WITH source AS (

    SELECT *
    FROM {{ source('ns', 'ITEM') }}
    {% if is_incremental() %}
  WHERE TRY_TO_TIMESTAMP_NTZ(LASTMODIFIEDDATE, 'DD-MM-YYYY HH24:MI') > (SELECT MAX(SILVER_UPDATED_ON_TS_UTC) FROM {{ this }})
    {% endif %}

),

renamed AS (

    SELECT
        MD5(CAST(ID AS VARCHAR))                                                    AS SURROGATE_KEY,
        NULLIF(TRIM(AMORTIZATIONPERIOD), '')                                        AS AMORTIZATION_PERIOD,
        NULLIF(TRIM(AMORTIZATIONTEMPLATE), '')                                      AS AMORTIZATION_TEMPLATE,
        NULLIF(TRIM(ATPMETHOD), '')                                                 AS ATPMETHOD,
        NULLIF(TRIM(BILLEXCHRATEVARIANCEACCT), '')                                  AS BILLEXCHRATEVARIANCEACCT,
        NULLIF(TRIM(BILLINGSCHEDULE), '')                                           AS BILLING_SCHEDULE,
        NULLIF(TRIM(BILLPRICEVARIANCEACCT), '')                                     AS BILL_PRICE_VARIANCE_ACCOUNT,
        NULLIF(TRIM(BILLQTYVARIANCEACCT), '')                                       AS BILL_QUANTITY_VARIANCE_ACCOUNT,
        CAST(CLASS AS NUMBER(38,0))                                                 AS CLASS,
        NULLIF(TRIM(COSTINGMETHOD), '')                                             AS COSTING_METHOD,
        NULLIF(TRIM(COSTINGMETHODDISPLAY), '')                                      AS COSTING_METHOD_DISPLAY,
        NULLIF(TRIM(COUNTRYOFMANUFACTURE), '')                                      AS COUNTRY_OF_MANUFACTURE,
        TRY_TO_DATE(CREATEDDATE)                                                    AS CREATED_DATE,
        NULLIF(TRIM(DEFERRALACCOUNT), '')                                           AS DEFERRAL_ACCOUNT,
        CAST(DEPARTMENT AS NUMBER(38,0))                                            AS DEPARTMENT,
        NULLIF(TRIM(DESCRIPTION), '')                                               AS DESCRIPTION,
        NULLIF(TRIM(DISPLAYNAME), '')                                               AS DISPLAY_NAME,
        ENFORCEQUANTITYINTERNALLY                                                   AS ENFORCE_QUANTITY_INTERNALLY,
        NULLIF(TRIM(EXPENSEACCOUNT), '')                                            AS EXPENSE_ACCOUNT,
        NULLIF(TRIM(EXPENSEAMORTIZATIONRULE), '')                                   AS EXPENSE_AMORTIZATION_RULE,
        NULLIF(TRIM(EXTERNALID), '')                                                AS EXTERNAL_ID,
        NULLIF(TRIM(FEATUREDDESCRIPTION), '')                                       AS FEATURED_DESCRIPTION,
        NULLIF(TRIM(FULLNAME), '')                                                  AS FULL_NAME,
        NULLIF(TRIM(GAINLOSSACCOUNT), '')                                           AS GAINLOSSACCOUNT,
        CAST(ID AS NUMBER(38,0))                                                    AS ID,
        NULLIF(TRIM(INCOMEACCOUNT), '')                                             AS INCOME_ACCOUNT,
        NULLIF(TRIM(ITEMID), '')                                                    AS ITEM_ID,
        NULLIF(TRIM(ITEMTYPE), '')                                                  AS ITEM_TYPE,
        TRY_TO_TIMESTAMP_NTZ(LASTMODIFIEDDATE, 'DD-MM-YYYY HH24:MI')  AS LAST_MODIFIED_DATE,
        NULLIF(TRIM(LOCATION), '')                                                  AS LOCATION,
        NULLIF(TRIM(MANUFACTURER), '')                                              AS MANUFACTURER,
        CAST(MAXIMUMQUANTITY AS NUMBER(38,6))                                       AS MAXIMUM_QUANTITY,
        NULLIF(TRIM(METATAGHTML), '')                                               AS METATAG_HTML,
        CAST(MINIMUMQUANTITY AS NUMBER(38,6))                                       AS MINIMUM_QUANTITY,
        NULLIF(TRIM(MPN), '')                                                       AS MPN,
        NULLIF(TRIM(NEXTAGCATEGORY), '')                                            AS NEXTAG_CATEGORY,
        NULLIF(TRIM(OVERALLQUANTITYPRICINGTYPE), '')                                AS OVERALL_QUANTITY_PRICING_TYPE,
        CAST(PARENT AS NUMBER(38,0))                                                AS PARENT,
        CAST(PREFERREDSTOCKLEVEL AS NUMBER(38,0))                                   AS PREFERRED_STOCK_LEVEL,
        CAST(PRICINGGROUP AS NUMBER(38,0))                                          AS PRICING_GROUP,
        NULLIF(TRIM(PRODPRICEVARIANCEACCT), '')                                     AS PRODPRICEVARIANCEACCT,
        NULLIF(TRIM(PRODQTYVARIANCEACCT), '')                                       AS PRODQTYVARIANCEACCT,
        NULLIF(TRIM(PROJECTEXPENSETYPE), '')                                        AS PROJECT_EXPENSE_TYPE,
        CAST(PROJECTTEMPLATE AS NUMBER(38,0))                                       AS PROJECT_TEMPLATE,
        NULLIF(TRIM(PURCHASEDESCRIPTION), '')                                       AS PURCHASE_DESCRIPTION,
        NULLIF(TRIM(PURCHASEPRICEVARIANCEACCT), '')                                 AS PURCHASE_PRICE_VARIANCE_ACCOUNT,
        CAST(PURCHASEUNIT AS NUMBER(38,0))                                          AS PURCHASE_UNIT,
        CAST(QUANTITYAVAILABLE AS NUMBER(38,6))                                     AS QUANTITY_AVAILABLE,
        CAST(QUANTITYBACKORDERED AS NUMBER(38,6))                                   AS QUANTITYBACKORDERED,
        CAST(QUANTITYCOMMITTED AS NUMBER(38,6))                                     AS QUANTITY_COMMITTED,
        CAST(QUANTITYONHAND AS NUMBER(38,6))                                        AS QUANTITYONHAND,
        CAST(QUANTITYONORDER AS NUMBER(38,6))                                       AS QUANTITY_ON_ORDER,
        NULLIF(TRIM(QUANTITYPRICINGSCHEDULE), '')                                   AS QUANTITY_PRICING_SCHEDULE,
        NULLIF(TRIM(RELATEDITEMSDESCRIPTION), '')                                   AS RELATED_ITEMS_DESCRIPTION,
        CAST(REORDERPOINT AS NUMBER(38,0))                                          AS REORDERPOINT,
        CAST(SALEUNIT AS NUMBER(38,0))                                              AS SALEUNIT,
        NULLIF(TRIM(SCRAPACCT), '')                                                 AS SCRAP_ACCOUNT,
        NULLIF(TRIM(SEARCHKEYWORDS), '')                                            AS SEARCHKEYWORDS,
        NULLIF(TRIM(SHIPINDIVIDUALLY), '')                                          AS SHIP_INDIVIDUALLY,
        NULLIF(TRIM(SHIPPACKAGE), '')                                               AS SHIP_PACKAGE,
        TRY_TO_NUMBER(SHIPPINGCOST, 38, 6)                                          AS SHIPPING_COST,
        NULLIF(TRIM(SHOPPINGPRODUCTFEED), '')                                       AS SHOPPING_PRODUCT_FEED,
        NULLIF(TRIM(SHOPZILLACATEGORYID), '')                                       AS SHOPZILLA_CATEGORY_ID,
        NULLIF(TRIM(SHOPZILLAPRODUCTFEED), '')                                      AS SHOPZILLA_PRODUCT_FEED,
        NULLIF(TRIM(SITEMAPPRIORITY), '')                                           AS SITEMAPPRIORITY,
        NULLIF(TRIM(STOCKDESCRIPTION), '')                                          AS STOCK_DESCRIPTION,
        NULLIF(TRIM(STOCKUNIT), '')                                                 AS STOCK_UNIT,
        NULLIF(TRIM(STOREDESCRIPTION), '')                                          AS STORE_DESCRIPTION,
        NULLIF(TRIM(STOREDETAILEDDESCRIPTION), '')                                  AS STOREDETAILEDDESCRIPTION,
        NULLIF(TRIM(STOREDISPLAYIMAGE), '')                                         AS STORE_DISPLAY_IMAGE,
        NULLIF(TRIM(STOREDISPLAYNAME), '')                                          AS STORE_DISPLAY_NAME,
        NULLIF(TRIM(STOREDISPLAYTHUMBNAIL), '')                                     AS STORE_DISPLAY_THUMBNAIL,
        NULLIF(TRIM(SUBSIDIARY), '')                                                AS SUBSIDIARY,
        NULLIF(TRIM(SUBTYPE), '')                                                   AS SUBTYPE,
        TRY_TO_NUMBER(TOTALVALUE, 38, 6)                                            AS TOTAL_VALUE,
        NULLIF(TRIM(UNBUILDVARIANCEACCOUNT), '')                                    AS UNBUILD_VARIANCE_ACCOUNT,
        NULLIF(TRIM(UNITSTYPE), '')                                                 AS UNITS_TYPE,
        NULLIF(TRIM(UPCCODE), '')                                                   AS UPC_CODE,
        TRY_TO_BOOLEAN(USECOMPONENTYIELD)                                           AS USE_COMPONENT_YIELD,
        TRY_TO_BOOLEAN(USEMARGINALRATES)                                            AS USEMARGINALRATES,
        NULLIF(TRIM(WEIGHT), '')                                                    AS WEIGHT,
        NULLIF(TRIM(WEIGHTUNIT), '')                                                AS WEIGHT_UNIT,
        NULLIF(TRIM(WEIGHTUNITS), '')                                               AS WEIGHT_UNITS,
        NULLIF(TRIM(WIPACCT), '')                                                   AS WIP_ACCOUNT,
        NULLIF(TRIM(WIPVARIANCEACCT), '')                                           AS WIP_VARIANCE_ACCOUNT,
        GENERATEACCRUALS                                                            AS GENERATE_ACCRUALS,
        CAST(LASTPURCHASEPRICE AS NUMBER(38,6))                                     AS LAST_PURCHASE_PRICE,
        CAST(HANDLINGCOST AS NUMBER(38,6))                                          AS HANDLING_COST,
        CAST(RECEIPTQUANTITYDIFF AS NUMBER(38,6))                                   AS RECEIPTQUANTITYDIFF,
        CAST(SHOPPINGDOTCOMCATEGORY AS NUMBER(38,0))                                AS SHOPPINGDOTCOMCATEGORY,
        FROOGLEPRODUCTFEED                                                          AS FROOGLE_PRODUCT_FEED,
        CAST(RESIDUAL AS NUMBER(38,0))                                              AS RESIDUAL,
        CAST(PURCHASEORDERAMOUNT AS NUMBER(38,6))                                   AS PURCHASE_ORDER_AMOUNT,
        CAST(RECEIPTQUANTITY AS NUMBER(38,6))                                       AS RECEIPT_QUANTITY,
        NULLIF(TRIM(EFFECTIVEBOMCONTROL), '')                                       AS EFFECTIVE_BOM_CONTROL,
        CAST(PURCHASEORDERQUANTITYDIFF AS NUMBER(38,6))                             AS PURCHASEORDERQUANTITYDIFF,
        NULLIF(TRIM(VENDORNAME), '')                                                AS VENDOR_NAME,
        ISFULFILLABLE                                                               AS IS_FULFILLABLE,
        EXCLUDEFROMSITEMAP                                                          AS EXCLUDEFROMSITEMAP,
        NULLIF(TRIM(YAHOOPRODUCTFEED), '')                                          AS YAHOO_PRODUCT_FEED,
        CREATEJOB                                                                   AS CREATE_JOB,
        NEXTAGPRODUCTFEED                                                           AS NEXTAG_PRODUCT_FEED,
        CAST(FXCOST AS NUMBER(38,6))                                                AS FX_COST,
        NULLIF(TRIM(SUPPLYREPLENISHMENTMETHOD), '')                                 AS SUPPLY_REPLENISHMENT_METHOD,
        ISONLINE                                                                    AS IS_ONLINE,
        INCLUDECHILDREN                                                             AS INCLUDECHILDREN,
        MATCHBILLTORECEIPT                                                          AS MATCH_BILL_TO_RECEIPT,
        ISINACTIVE                                                                  AS IS_INACTIVE,
        CAST(PURCHASEORDERQUANTITY AS NUMBER(38,6))                                 AS PURCHASE_ORDER_QUANTITY,
        PRINTITEMS                                                                  AS PRINT_ITEMS,
        CAST(COST AS NUMBER(38,6))                                                  AS COST,
        CAST(RECEIPTAMOUNT AS NUMBER(38,6))                                         AS RECEIPT_AMOUNT,
        CAST(AVERAGECOST AS NUMBER(38,6))                                           AS AVERAGE_COST,
        CAST(CREATEEXPENSEPLANSON AS NUMBER(38,0))                                  AS CREATEEXPENSEPLANSON,
        AUTOLEADTIME                                                                AS AUTOLEADTIME,
        CAST(DROPSHIPEXPENSEACCOUNT AS NUMBER(38,0))                                AS DROP_SHIP_EXPENSE_ACCOUNT,
        NULLIF(TRIM(SUPPLYTYPE), '')                                                AS SUPPLY_TYPE,
        CAST(CUSTITEMBRAND AS NUMBER(38,0))                                         AS CUSTITEMBRAND,
        NULLIF(TRIM(PERIODICLOTSIZEDAYS), '')                                       AS PERIODIC_LOT_SIZE_DAYS,
        CAST(COSTCATEGORY AS NUMBER(38,0))                                          AS COST_CATEGORY,
        NULLIF(TRIM(CUSTITEM_VIDEO_URL), '')                                        AS CUSTITEM_VIDEO_URL,
        CAST(CUSTITEM_MCGF_WEEKSSUPPLY AS NUMBER(38,0))                             AS CUSTITEM_MCGF_WEEKSSUPPLY,
        NULLIF(TRIM(MANUFACTURERTAXID), '')                                         AS MANUFACTURER_TAX_ID,
        CAST(TOTALQUANTITYONHAND AS NUMBER(38,6))                                   AS TOTALQUANTITYONHAND,
        NULLIF(TRIM(COSTESTIMATETYPE), '')                                          AS COST_ESTIMATE_TYPE,
        NULLIF(TRIM(MATRIXOPTIONCUSTITEMCUSTITEM_PLACOLOR), '')                     AS MATRIXOPTIONCUSTITEMCUSTITEM_PLACOLOR,
        NULLIF(TRIM(RESCHEDULEINDAYS), '')                                          AS RESCHEDULEINDAYS,
        CAST(CUSTITEM_MCGF_WEBITEMID AS NUMBER(38,0))                               AS CUSTITEM_MCGF_WEBITEMID,
        ISLOTITEM                                                                   AS IS_LOT_ITEM,
        NULLIF(TRIM(CUSTITEMCUSTOMITEM_SCANNERTYPE), '')                            AS CUSTITEMCUSTOMITEM_SCANNERTYPE,
        NULLIF(TRIM(DEMANDSOURCE), '')                                              AS DEMAND_SOURCE,
        CAST(CUSTITEMCUSTOMITEM_TYPE AS NUMBER(38,0))                               AS CUSTITEMCUSTOMITEM_TYPE,
        DEPOSIT                                                                     AS DEPOSIT,
        NULLIF(TRIM(CUSTITEM_CSEG_VENDORTYPE), '')                                  AS CUSTITEM_CSEG_VENDORTYPE,
        ISSPECIALWORKORDERITEM                                                      AS IS_SPECIAL_WORK_ORDER_ITEM,
        NULLIF(TRIM(MATRIXOPTIONCUSTITEMAPPARELSIZE), '')                           AS MATRIXOPTIONCUSTITEMAPPARELSIZE,
        NULLIF(TRIM(MATRIXOPTIONCUSTITEM13), '')                                    AS MATRIXOPTIONCUSTITEM13,
        NULLIF(TRIM(MATRIXOPTIONCUSTITEM14), '')                                    AS MATRIXOPTIONCUSTITEM14,
        NULLIF(TRIM(CUSTITEMSEASON), '')                                            AS CUSTITEMSEASON,
        CONTINGENTREVENUEHANDLING                                                   AS CONTINGENT_REVENUE_HANDLING,
        CAST(MAXDONATIONAMOUNT AS NUMBER(38,6))                                     AS MAXDONATIONAMOUNT,
        NULLIF(TRIM(CUSTITEMCOLOR), '')                                             AS CUSTITEMCOLOR,
        CAST(CUSTITEM_MANUFACTURER AS NUMBER(38,0))                                 AS CUSTITEM_MANUFACTURER,
        _FIVETRAN_SYNCED                                                            AS FIVETRAN_SYNCED,
        NULLIF(TRIM(DEMANDTIMEFENCE), '')                                           AS DEMAND_TIME_FENCE,
        CAST(CUSTITEMTYPE AS NUMBER(38,0))                                          AS CUSTITEMTYPE,
        CAST(CONSUMPTIONUNIT AS NUMBER(38,6))                                       AS CONSUMPTION_UNIT,
        ENFORCEMINQTYINTERNALLY                                                     AS ENFORCE_MINQTY_INTERNALLY,
        SEASONALDEMAND                                                              AS SEASONAL_DEMAND,
        CAST(CUSTITEM_MCGF_SHOPCODE AS NUMBER(38,0))                                AS CUSTITEM_MCGF_SHOPCODE,
        CAST(DISTRIBUTIONCATEGORY AS NUMBER(38,0))                                  AS DISTRIBUTION_CATEGORY,
        CAST(CUSTITEM_WRM_ITEM_WARRANTYTERMS AS NUMBER(38,0))                       AS CUSTITEM_WRM_ITEM_WARRANTYTERMS,
        VSOEDELIVERED                                                               AS VSOE_DELIVERED,
        NULLIF(TRIM(CUSTITEMIMAGECODE), '')                                         AS CUSTITEMIMAGECODE,
        NULLIF(TRIM(SUPPLYLOTSIZINGMETHOD), '')                                     AS SUPPLY_LOT_SIZING_METHOD,
        NULLIF(TRIM(CUSTITEM_SPECIFICATIONS), '')                                   AS CUSTITEM_SPECIFICATIONS,
        ISDROPSHIPITEM                                                              AS IS_DROP_SHIP_ITEM,
        NULLIF(TRIM(MATRIXOPTIONCUSTITEM_HELMETSIZE), '')                           AS MATRIXOPTIONCUSTITEM_HELMETSIZE,
        AUTOREORDERPOINT                                                            AS AUTOREORDERPOINT,
        NULLIF(TRIM(CUSTITEM_HELMETSIZE), '')                                       AS CUSTITEM_HELMETSIZE,
        NULLIF(TRIM(MATRIXOPTIONCUSTITEM26), '')                                    AS MATRIXOPTIONCUSTITEM26,
        NULLIF(TRIM(MATRIXOPTIONCUSTITEM27), '')                                    AS MATRIXOPTIONCUSTITEM27,
        NULLIF(TRIM(CUSTITEM_PRODUCTREVIEWS2), '')                                  AS CUSTITEM_PRODUCTREVIEWS2,
        NULLIF(TRIM(CUSTITEM_WRM_ITEM_WARRANTYEXPIRES), '')                         AS CUSTITEM_WRM_ITEM_WARRANTYEXPIRES,
        NULLIF(TRIM(CUSTITEM_PRODUCTREVIEWS1), '')                                  AS CUSTITEM_PRODUCTREVIEWS1,
        NULLIF(TRIM(MATRIXOPTIONCUSTITEM22), '')                                    AS MATRIXOPTIONCUSTITEM22,
        CAST(REVENUEALLOCATIONGROUP AS NUMBER(38,0))                                AS REVENUE_ALLOCATION_GROUP,
        NULLIF(TRIM(MATRIXOPTIONCUSTITEM23), '')                                    AS MATRIXOPTIONCUSTITEM23,
        CAST(CUSTITEM_CUSTOM_ALTIMAGE1 AS NUMBER(38,0))                             AS CUSTITEM_CUSTOM_ALTIMAGE1,
        CAST(CUSTITEM_MCGF_AGEGROUP AS NUMBER(38,0))                                AS CUSTITEM_MCGF_AGEGROUP,
        NULLIF(TRIM(MATRIXOPTIONCUSTITEM24), '')                                    AS MATRIXOPTIONCUSTITEM24,
        CAST(REVRECSCHEDULE AS NUMBER(38,0))                                        AS REVREC_SCHEDULE,
        CAST(CUSTITEM_MCGF_GTIN AS NUMBER(38,0))                                    AS CUSTITEM_MCGF_GTIN,
        NULLIF(TRIM(MATRIXOPTIONCUSTITEM25), '')                                    AS MATRIXOPTIONCUSTITEM25,
        NULLIF(TRIM(MATRIXOPTIONCUSTITEM20), '')                                    AS MATRIXOPTIONCUSTITEM20,
        NULLIF(TRIM(MATRIXOPTIONCUSTITEMCOLOR), '')                                 AS MATRIXOPTIONCUSTITEMCOLOR,
        NULLIF(TRIM(CUSTITEM6), '')                                                 AS CUSTITEM6,
        NULLIF(TRIM(FORWARDCONSUMPTIONDAYS), '')                                    AS FORWARD_CONSUMPTION_DAYS,
        CAST(CUSTITEM_MCGF_CONDITION AS NUMBER(38,0))                               AS CUSTITEM_MCGF_CONDITION,
        CAST(CUSTITEM1 AS NUMBER(38,0))                                             AS CUSTITEM1,
        NULLIF(TRIM(MATRIXOPTIONCUSTITEM19), '')                                    AS MATRIXOPTIONCUSTITEM19,
        NULLIF(TRIM(CUSTITEMCUSTITEM_PRINTERCOLOR), '')                             AS CUSTITEMCUSTITEM_PRINTERCOLOR,
        AUTOEXPANDKITFORREVENUEMGMT                                                 AS AUTO_EXPAND_KIT_FOR_REVENUE_MANAGEMENT,
        NULLIF(TRIM(MATRIXOPTIONCUSTITEM18), '')                                    AS MATRIXOPTIONCUSTITEM18,
        DEFERREVREC                                                                 AS DEFERREVREC,
        CAST(CUSTITEMCUSTOMITEM_CATEGORY AS NUMBER(38,0))                           AS CUSTITEMCUSTOMITEM_CATEGORY,
        NULLIF(TRIM(INTERCODEFREVACCOUNT), '')                                      AS INTERCO_DEFREV_ACCOUNT,
        NULLIF(TRIM(REVRECLASSFXACCOUNT), '')                                       AS REVRECLASSFXACCOUNT,
        LASTINVENTORYCOSTINGCORRECTIONDATE                                          AS LAST_INVENTORY_COSTING_CORRECTION_DATE,
        NULLIF(TRIM(MATRIXITEMNAMETEMPLATE), '')                                    AS MATRIX_ITEM_NAME_TEMPLATE,
        CAST(CUSTITEMCATALOG AS NUMBER(38,0))                                       AS CUSTITEMCATALOG,
        CAST(TRANSFERPRICE AS NUMBER(38,6))                                         AS TRANSFERPRICE,
        CAST(CUSTRETURNVARIANCEACCOUNT AS NUMBER(38,0))                             AS CUSTRETURNVARIANCEACCOUNT,
        CAST(REVRECFORECASTRULE AS NUMBER(38,0))                                    AS REVREC_FORECAST_RULE,
        TRACKLANDEDCOST                                                             AS TRACKLANDEDCOST,
        CUSTITEM_WRM_ITEM_TRACKWARRANTY                                             AS CUSTITEM_WRM_ITEM_TRACKWARRANTY,
        NULLIF(TRIM(CUSTITEM_STOREDISPLAYNAME_SPANISH), '')                         AS CUSTITEM_STOREDISPLAYNAME_SPANISH,
        CAST(CREATEREVENUEPLANSON AS NUMBER(38,0))                                  AS CREATEREVENUEPLANSON,
        NULLIF(TRIM(MATRIXOPTIONCUSTITEMCUSTITEM_POWERSUPPLY), '')                  AS MATRIXOPTIONCUSTITEMCUSTITEM_POWERSUPPLY,
        CAST(ITEMREVENUECATEGORY AS NUMBER(38,0))                                   AS ITEM_REVENUE_CATEGORY,
        CAST(DEFERREDREVENUEACCOUNT AS NUMBER(38,0))                                AS DEFERRED_REVENUE_ACCOUNT,
        NULLIF(TRIM(SCHEDULEBNUMBER), '')                                           AS SCHEDULEB_NUMBER,
        CAST(CUSTITEMSHOPBY AS NUMBER(38,0))                                        AS CUSTITEMSHOPBY,
        AVAILABLETOPARTNERS                                                         AS AVAILABLETOPARTNERS,
        CAST(INTERCOEXPENSEACCOUNT AS NUMBER(38,0))                                 AS INTERCO_EXPENSE_ACCOUNT,
        NULLIF(TRIM(FRAUDRISK), '')                                                 AS FRAUDRISK,
        DIRECTREVENUEPOSTING                                                        AS DIRECTREVENUEPOSTING,
        CAST(DEMANDMODIFIER AS NUMBER(38,0))                                        AS DEMANDMODIFIER,
        NULLIF(TRIM(RESCHEDULEOUTDAYS), '')                                         AS RESCHEDULEOUTDAYS,
        CAST(ALTERNATEDEMANDSOURCEITEM AS NUMBER(38,0))                             AS ALTERNATE_DEMAND_SOURCE_ITEM,
        ISDONATIONITEM                                                              AS IS_DONATION_ITEM,
        CAST(CUSTITEM_ZOOM_SMALL AS NUMBER(38,0))                                   AS CUSTITEM_ZOOM_SMALL,
        BUILDENTIREASSEMBLY                                                         AS BUILDENTIREASSEMBLY,
        NULLIF(TRIM(PERIODICLOTSIZETYPE), '')                                       AS PERIODIC_LOT_SIZE_TYPE,
        NULLIF(TRIM(CUSTITEM22), '')                                                AS CUSTITEM22,
        NULLIF(TRIM(CUSTITEM23), '')                                                AS CUSTITEM23,
        NULLIF(TRIM(CUSTITEM20), '')                                                AS CUSTITEM20,
        NULLIF(TRIM(CUSTITEM21), '')                                                AS CUSTITEM21,
        ISSERIALITEM                                                                AS IS_SERIAL_ITEM,
        NULLIF(TRIM(CUSTITEM26), '')                                                AS CUSTITEM26,
        NULLIF(TRIM(CUSTITEM27), '')                                                AS CUSTITEM27,
        CAST(CUSTITEMCUSTITEM_BRAND AS NUMBER(38,0))                                AS CUSTITEMCUSTITEM_BRAND,
        NULLIF(TRIM(CUSTITEM24), '')                                                AS CUSTITEM24,
        NULLIF(TRIM(CUSTITEM25), '')                                                AS CUSTITEM25,
        ISPHANTOM                                                                   AS ISPHANTOM,
        CUSTITEM_IS_OUTFIT                                                          AS CUSTITEM_IS_OUTFIT,
        CAST(CUSTITEM_MERCH_ITM_DEPT AS NUMBER(38,0))                               AS CUSTITEM_MERCH_ITM_DEPT,
        USEBINS                                                                     AS USEBINS,
        CAST(CUSTITEM10 AS NUMBER(38,0))                                            AS CUSTITEM10,
        SHOWDEFAULTDONATIONAMOUNT                                                   AS SHOW_DEFAULT_DONATION_AMOUNT,
        NULLIF(TRIM(CUSTITEM19), '')                                                AS CUSTITEM19,
        CAST(CUSTITEM17 AS NUMBER(38,0))                                            AS CUSTITEM17,
        NULLIF(TRIM(PREFERENCECRITERION), '')                                       AS PREFERENCECRITERION,
        NULLIF(TRIM(CUSTITEM18), '')                                                AS CUSTITEM18,
        NULLIF(TRIM(CUSTITEMSEASONTEST), '')                                        AS CUSTITEMSEASONTEST,
        CUSTITEM16                                                                  AS CUSTITEM16,
        NULLIF(TRIM(CUSTITEM13), '')                                                AS CUSTITEM13,
        NULLIF(TRIM(CUSTITEM14), '')                                                AS CUSTITEM14,
        CAST(CUSTITEM_MERCH_ITM_SUBC AS NUMBER(38,0))                               AS CUSTITEM_MERCH_ITM_SUBC,
        CAST(SAFETYSTOCKLEVELDAYS AS NUMBER(38,0))                                  AS SAFETYSTOCKLEVELDAYS,
        NULLIF(TRIM(CUSTITEM_CSEGCSEGCUSTSEG_CUS), '')                              AS CUSTITEM_CSEGCSEGCUSTSEG_CUS,
        CAST(CUSTITEM_MERCH_ITM_CLASS AS NUMBER(38,0))                              AS CUSTITEM_MERCH_ITM_CLASS,
        _FIVETRAN_DELETED                                                           AS FIVETRAN_DELETED,
        NULLIF(TRIM(CUSTITEMCUSTITEM_POWERSUPPLY), '')                              AS CUSTITEMCUSTITEM_POWERSUPPLY,
        CAST(CUSTITEM_ZOOM_BIG AS NUMBER(38,0))                                     AS CUSTITEM_ZOOM_BIG,
        NULLIF(TRIM(VSOEPERMITDISCOUNT), '')                                        AS VSOEPERMITDISCOUNT,
        CUSTITEM_MCGF_SALEPRICEDATE                                                 AS CUSTITEM_MCGF_SALEPRICEDATE,
        NULLIF(TRIM(MANUFACTURERTARIFF), '')                                        AS MANUFACTURERTARIFF,
        MANUFACTURINGCHARGEITEM                                                     AS MANUFACTURINGCHARGEITEM,
        CAST(CUSTITEM_POPUP AS NUMBER(38,0))                                        AS CUSTITEM_POPUP,
        NULLIF(TRIM(OVERHEADTYPE), '')                                              AS OVERHEADTYPE,
        NULLIF(TRIM(BACKWARDCONSUMPTIONDAYS), '')                                   AS BACKWARDCONSUMPTIONDAYS,
        CAST(CUSTITEMCATEGORY AS NUMBER(38,0))                                      AS CUSTITEMCATEGORY,
        CAST(CUSTITEM_MCGF_SALEPRICE AS NUMBER(38,6))                               AS CUSTITEM_MCGF_SALEPRICE,
        CAST(VENDRETURNVARIANCEACCOUNT AS NUMBER(38,0))                             AS VENDRETURNVARIANCEACCOUNT,
        PRODUCER                                                                    AS PRODUCER,
        NULLIF(TRIM(CUSTITEM_CSEGCUSTSEG_CHANNEL), '')                              AS CUSTITEM_CSEGCUSTSEG_CHANNEL,
        NULLIF(TRIM(CUSTITEMCUSTITEM_PLACOLOR), '')                                 AS CUSTITEMCUSTITEM_PLACOLOR,
        NULLIF(TRIM(MATRIXTYPE), '')                                                AS MATRIX_TYPE,
        CAST(CUSTITEMGENDER AS NUMBER(38,0))                                        AS CUSTITEMGENDER,
        ROUNDUPASCOMPONENT                                                          AS ROUNDUPASCOMPONENT,
        NULLIF(TRIM(SUPPLYTIMEFENCE), '')                                           AS SUPPLY_TIME_FENCE,
        CAST(INTERCOINCOMEACCOUNT AS NUMBER(38,0))                                  AS INTERCO_INCOME_ACCOUNT,
        NULLIF(TRIM(FIXEDLOTSIZE), '')                                              AS FIXED_LOT_SIZE,
        DONTSHOWPRICE                                                               AS DONTSHOWPRICE,
        NULLIF(TRIM(CUSTITEMAPPARELSIZE), '')                                       AS CUSTITEMAPPARELSIZE,
        CAST(DISTRIBUTIONNETWORK AS NUMBER(38,0))                                   AS DISTRIBUTION_NETWORK,
        NULLIF(TRIM(CUSTITEM_NSPBCS_ITEM_PLANNING_CAT), '')                         AS CUSTITEM_NSPBCS_ITEM_PLANNING_CAT,
        NULLIF(TRIM(VSOESOPGROUP), '')                                              AS VSOESOPGROUP,
        CAST(CUSTITEM_CUSTOM_ALTIMAGETH AS NUMBER(38,0))                            AS CUSTITEM_CUSTOM_ALTIMAGETH,
        CAST(REVENUERECOGNITIONRULE AS NUMBER(38,0))                                AS REVENUE_RECOGNITION_RULE,
        CAST(ASSETACCOUNT AS NUMBER(38,0))                                          AS ASSET_ACCOUNT,
        NULLIF(TRIM(CUSTITEM_WRM_ITEM_REPAIREDITEM), '')                            AS CUSTITEM_WRM_ITEM_REPAIREDITEM,
        NULLIF(TRIM(NOPRICEMESSAGE), '')                                            AS NOPRICEMESSAGE,
        NULLIF(TRIM(CUSTITEM_MCGF_TAXUS), '')                                       AS CUSTITEM_MCGF_TAXUS,
        COPYDESCRIPTION                                                             AS COPY_DESCRIPTION,
        NULLIF(TRIM(MATRIXOPTIONCUSTITEMCUSTOMITEM_SCANNERTYPE), '')                AS MATRIXOPTIONCUSTITEMCUSTOMITEM_SCANNERTYPE,
        AUTOPREFERREDSTOCKLEVEL                                                     AS AUTO_PREFERRED_STOCK_LEVEL,
        CAST(PREFERREDLOCATION AS NUMBER(38,0))                                     AS PREFERRED_LOCATION,
        CAST(REORDERMULTIPLE AS NUMBER(38,0))                                       AS REORDERMULTIPLE,
        TRY_TO_NUMBER(VSOEPRICE, 38, 6)                                             AS VSOE_PRICE,
        CAST(COSTESTIMATE AS NUMBER(38,6))                                          AS COST_ESTIMATE,
        ISSPECIALORDERITEM                                                          AS IS_SPECIAL_ORDER_ITEM,
        NULLIF(TRIM(SCHEDULEBQUANTITY), '')                                         AS SCHEDULEB_QUANTITY,
        NULLIF(TRIM(URLCOMPONENT), '')                                              AS URL_COMPONENT,
        CAST(CUSTITEM_MERCH_ITM_DIV AS NUMBER(38,0))                                AS CUSTITEM_MERCH_ITM_DIV

    FROM source

),

final AS (

    SELECT
        renamed.*,

        -- Audit metadata
        {% if is_incremental() %}
        COALESCE(
            (SELECT MIN(existing.SILVER_CREATED_ON_TS_UTC)
             FROM {{ this }} existing
             WHERE existing.SURROGATE_KEY = renamed.SURROGATE_KEY),
            CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())
        )                                                                       AS SILVER_CREATED_ON_TS_UTC,
        {% else %}
        CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())                                    AS SILVER_CREATED_ON_TS_UTC,
        {% endif %}
        CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())                                    AS SILVER_UPDATED_ON_TS_UTC,
        CAST(NULL AS TIMESTAMP_NTZ)                               AS SILVER_DELETED_ON_TS_UTC

    FROM renamed

)

SELECT * FROM final
