-- The output have been generated with the assistance of Claude at 2026-06-16T10:00:00Z UTC. The content has been verified by the designated engineer.

{{
  config(
    materialized         = 'incremental',
    unique_key           = 'SURROGATE_KEY',
    incremental_strategy = 'merge',
    on_schema_change     = 'fail',
    tags                 = ['silver', 'staging', 'netsuite']
  )
}}

{#
  Model   : stg_ns_transaction
  Layer   : staging
  Grain   : 1 row per STG_NS_TRANSACTION
  Schema  : static (explicit column list from Silver LLD)
  Cleaning: inline (TransformationRule expressions from Silver LLD)
  Source  : {{ source('ns', 'TRANSACTION') }}
  Watermark: LASTMODIFIEDDATE
#}

WITH source AS (

    SELECT *
    FROM {{ source('ns', 'TRANSACTION') }}
    {% if is_incremental() %}
    WHERE LASTMODIFIEDDATE > (SELECT MAX(SILVER_UPDATED_ON_TS_UTC) FROM {{ this }})
    {% endif %}

),

renamed AS (

    SELECT
        MD5(CAST(ID AS VARCHAR))                                                    AS SURROGATE_KEY,
        CAST(ID AS NUMBER(38,0))                                                    AS ID,
        NULLIF(TRIM(ABBREVTYPE), '')                                                AS ABBREVTYPE,
        NULLIF(TRIM(ACCOUNTBASEDNUMBER), '')                                        AS ACCOUNTBASEDNUMBER,
        NULLIF(TRIM(ACTIONITEM), '')                                                AS ACTIONITEM,
        TRY_TO_DATE(ACTUALPRODUCTIONENDDATE)                                        AS ACTUAL_PRODUCTION_END_DATE,
        TRY_TO_DATE(ACTUALPRODUCTIONSTARTDATE)                                      AS ACTUAL_PRODUCTION_START_DATE,
        ACTUALSHIPDATE                                                              AS ACTUAL_SHIP_DATE,
        NULLIF(TRIM(ALTSALESRANGEHIGH), '')                                         AS ALTSALESRANGEHIGH,
        NULLIF(TRIM(ALTSALESRANGELOW), '')                                          AS ALTSALESRANGELOW,
        CAST(ALTSALESTOTAL AS NUMBER(38,6))                                         AS ALTSALESTOTAL,
        CAST(AMOUNTUNBILLED AS NUMBER(38,6))                                        AS AMOUNTUNBILLED,
        NULLIF(TRIM(APPLYPICKDECOMPOSITION), '')                                    AS APPLYPICKDECOMPOSITION,
        CAST(APPROVALSTATUS AS NUMBER(38,0))                                        AS APPROVAL_STATUS,
        ASOFDATE                                                                    AS AS_OF_DATE,
        AUTOCALCULATELAG                                                            AS AUTOCALCULATELAG,
        CAST(BALSEGSTATUS AS NUMBER(38,0))                                          AS BALSEGSTATUS,
        BIDCLOSEDATE                                                                AS BIDCLOSEDATE,
        BIDOPENDATE                                                                 AS BIDOPENDATE,
        CAST(BILLINGADDRESS AS NUMBER(38,0))                                        AS BILLING_ADDRESS,
        BILLINGSTATUS                                                               AS BILLING_STATUS,
        NULLIF(TRIM(BULKPROCSUBMISSION), '')                                        AS BULKPROCSUBMISSION,
        NULLIF(TRIM(BUYINGREASON), '')                                              AS BUYINGREASON,
        NULLIF(TRIM(BUYINGTIMEFRAME), '')                                           AS BUYINGTIMEFRAME,
        CLOSEDATE                                                                   AS CLOSEDATE,
        CAST(COMMITTED AS NUMBER(38,0))                                             AS "COMMITTED",
        TRY_TO_TIMESTAMP_NTZ(COMPLETEDDATETIME)                                     AS COMPLETED_DATETIME,
        COMPLIANT                                                                   AS COMPLIANT,
        CONTRACTCOSTACCRUALDATE                                                     AS CONTRACT_COST_ACCRUAL_DATE,
        TRY_TO_NUMBER(CONTRACTCOSTAMOUNT, 38, 6)                                    AS CONTRACT_COST_AMOUNT,
        NULLIF(TRIM(CONTRACTDEFERREDEXPENSEACCT), '')                               AS CONTRACT_DEFERRED_EXPENSE_ACCOUNT,
        NULLIF(TRIM(CONTRACTEXPENSEACCT), '')                                       AS CONTRACT_EXPENSE_ACCOUNT,
        NULLIF(TRIM(CONTRACTEXPENSESOURCEACCT), '')                                 AS CONTRACT_EXPENSE_SOURCE_ACCOUNT,
        CAST(COUPONCODE AS NUMBER(38,0))                                            AS COUPONCODE,
        CAST(CREATEDBY AS NUMBER(38,0))                                             AS CREATED_BY,
        CREATEDDATE                                                                 AS CREATED_DATE,
        TRY_TO_TIMESTAMP_NTZ(CREATEDDATETIME)                                       AS CREATED_DATETIME,
        CREATEDFROMMERGE                                                            AS CREATEDFROMMERGE,
        CAST(CURRENCY AS NUMBER(38,0))                                              AS CURRENCY,
        CAST(CUSTBODY10 AS NUMBER(38,0))                                            AS CUSTBODY10,
        CUSTBODY11                                                                  AS CUSTBODY11,
        NULLIF(TRIM(CUSTBODY12), '')                                                AS CUSTBODY12,
        NULLIF(TRIM(CUSTBODY13), '')                                                AS CUSTBODY13,
        NULLIF(TRIM(CUSTBODY14), '')                                                AS CUSTBODY14,
        NULLIF(TRIM(CUSTBODY15), '')                                                AS CUSTBODY15,
        NULLIF(TRIM(CUSTBODY16), '')                                                AS CUSTBODY16,
        NULLIF(TRIM(CUSTBODY17), '')                                                AS CUSTBODY17,
        NULLIF(TRIM(CUSTBODY18), '')                                                AS CUSTBODY18,
        NULLIF(TRIM(CUSTBODY19), '')                                                AS CUSTBODY19,
        NULLIF(TRIM(CUSTBODY2), '')                                                 AS CUSTBODY2,
        CAST(CUSTBODY20 AS NUMBER(38,0))                                            AS CUSTBODY20,
        NULLIF(TRIM(CUSTBODY21), '')                                                AS CUSTBODY21,
        CAST(CUSTBODY3 AS NUMBER(38,0))                                             AS CUSTBODY3,
        CUSTBODY4                                                                   AS CUSTBODY4,
        CUSTBODY5                                                                   AS CUSTBODY5,
        CUSTBODY6                                                                   AS CUSTBODY6,
        CUSTBODY7                                                                   AS CUSTBODY7,
        NULLIF(TRIM(CUSTBODY8), '')                                                 AS CUSTBODY8,
        CAST(CUSTBODY9 AS NUMBER(38,0))                                             AS CUSTBODY9,
        CAST(CUSTBODY_ABI_CONSOLIDATION_REC AS NUMBER(38,0))                        AS CUSTBODY_ABI_CONSOLIDATION_REC,
        NULLIF(TRIM(CUSTBODY_ABI_TESTCONTACTLIST), '')                              AS CUSTBODY_ABI_TESTCONTACTLIST,
        CAST(CUSTBODY_ACC_APPROVAL_ROUTE AS NUMBER(38,0))                           AS CUSTBODY_ACC_APPROVAL_ROUTE,
        CAST(CUSTBODY_ACC_APPROVER_CUR_INDEX AS NUMBER(38,0))                       AS CUSTBODY_ACC_APPROVER_CUR_INDEX,
        CUSTBODY_ACC_APPROVER_CUR_REJC                                              AS CUSTBODY_ACC_APPROVER_CUR_REJC,
        CUSTBODY_ACC_APPROVER_DELEGATE_DATE                                         AS CUSTBODY_ACC_APPROVER_DELEGATE_DATE,
        CUSTBODY_ACC_APPROVER_REMINDER_DATE                                         AS CUSTBODY_ACC_APPROVER_REMINDER_DATE,
        NULLIF(TRIM(CUSTBODY_ACC_CREATED_FROM), '')                                 AS CUSTBODY_ACC_CREATED_FROM,
        CAST(CUSTBODY_ACC_CURRENT_APPROVAL_STEP AS NUMBER(38,0))                    AS CUSTBODY_ACC_CURRENT_APPROVAL_STEP,
        NULLIF(TRIM(CUSTBODY_ACC_ICJE_APPROVAL_ERROR), '')                          AS CUSTBODY_ACC_ICJE_APPROVAL_ERROR,
        CAST(CUSTBODY_ACC_ICJE_CREATED_BY AS NUMBER(38,0))                          AS CUSTBODY_ACC_ICJE_CREATED_BY,
        NULLIF(TRIM(CUSTBODY_ACC_ICJE_LIST_OF_APPROVERS), '')                       AS CUSTBODY_ACC_ICJE_LIST_OF_APPROVERS,
        CAST(CUSTBODY_ACC_ICJE_PRIMARY_APPROVER AS NUMBER(38,0))                    AS CUSTBODY_ACC_ICJE_PRIMARY_APPROVER,
        NULLIF(TRIM(CUSTBODY_ACC_ICJE_REJECT_REASON), '')                           AS CUSTBODY_ACC_ICJE_REJECT_REASON,
        NULLIF(TRIM(CUSTBODY_ACC_ICJE_REJECTED_BY), '')                             AS CUSTBODY_ACC_ICJE_REJECTED_BY,
        NULLIF(TRIM(CUSTBODY_ACC_ICJE_SECOND_APPROVER), '')                         AS CUSTBODY_ACC_ICJE_SECOND_APPROVER,
        CUSTBODY_ACC_ICJE_SUBMITTED_FOR_APP                                         AS CUSTBODY_ACC_ICJE_SUBMITTED_FOR_APP,
        CAST(CUSTBODY_ACC_MFJE_CREATEDFROM AS NUMBER(38,0))                         AS CUSTBODY_ACC_MFJE_CREATEDFROM,
        NULLIF(TRIM(CUSTBODY_ACC_MR_TASK_ID), '')                                   AS CUSTBODY_ACC_MR_TASK_ID,
        CAST(CUSTBODY_ACC_REL_IMP_QUEUE AS NUMBER(38,0))                            AS CUSTBODY_ACC_REL_IMP_QUEUE,
        CAST(CUSTBODY_ACC_REL_REMIT_REC AS NUMBER(38,0))                            AS CUSTBODY_ACC_REL_REMIT_REC,
        NULLIF(TRIM(CUSTBODY_ACC_REMIT_TEXT), '')                                   AS CUSTBODY_ACC_REMIT_TEXT,
        NULLIF(TRIM(CUSTBODY_ACC_TAP_DELGTN_REASON), '')                            AS CUSTBODY_ACC_TAP_DELGTN_REASON,
        CUSTBODY_ACC_TAP_EMAIL_DELGTN                                               AS CUSTBODY_ACC_TAP_EMAIL_DELGTN,
        CAST(CUSTBODY_ACC_TRAN_CINV_REF AS NUMBER(38,0))                            AS CUSTBODY_ACC_TRAN_CINV_REF,
        CAST(CUSTBODY_ACC_TRANSAPP_REQUESTOR AS NUMBER(38,0))                       AS CUSTBODY_ACC_TRANSAPP_REQUESTOR,
        NULLIF(TRIM(CUSTBODY_AP_OPP_EST_TEAM_SIZE), '')                             AS CUSTBODY_AP_OPP_EST_TEAM_SIZE,
        NULLIF(TRIM(CUSTBODY_AP_TRANS_SERV_TYPE), '')                               AS CUSTBODY_AP_TRANS_SERV_TYPE,
        NULLIF(TRIM(CUSTBODY_BM_BUDGET_CONTROL), '')                                AS CUSTBODY_BM_BUDGET_CONTROL,
        NULLIF(TRIM(CUSTBODY_BM_BUDGET_CURRENT), '')                                AS CUSTBODY_BM_BUDGET_CURRENT,
        NULLIF(TRIM(CUSTBODY_BM_BUDGET_NAME), '')                                   AS CUSTBODY_BM_BUDGET_NAME,
        NULLIF(TRIM(CUSTBODY_BM_BUDGET_ORIGINAL), '')                               AS CUSTBODY_BM_BUDGET_ORIGINAL,
        NULLIF(TRIM(CUSTBODY_BM_BUDGET_RANGE), '')                                  AS CUSTBODY_BM_BUDGET_RANGE,
        CUSTBODY_BM_BUDGETDATE                                                      AS CUSTBODY_BM_BUDGETDATE,
        NULLIF(TRIM(CUSTBODY_BM_BUDGETLASTCHECK), '')                               AS CUSTBODY_BM_BUDGETLASTCHECK,
        CAST(CUSTBODY_BM_BUDGETPERIOD AS NUMBER(38,0))                              AS CUSTBODY_BM_BUDGETPERIOD,
        NULLIF(TRIM(CUSTBODY_BM_BUDGETSTATUS), '')                                  AS CUSTBODY_BM_BUDGETSTATUS,
        NULLIF(TRIM(CUSTBODY_BM_CURRENT_BUDGET_ID), '')                             AS CUSTBODY_BM_CURRENT_BUDGET_ID,
        NULLIF(TRIM(CUSTBODY_BM_DUP_PEN_APPROVAL), '')                              AS CUSTBODY_BM_DUP_PEN_APPROVAL,
        NULLIF(TRIM(CUSTBODY_BM_FINANCIAL_YEAR), '')                                AS CUSTBODY_BM_FINANCIAL_YEAR,
        NULLIF(TRIM(CUSTBODY_BM_FLD_TRAN_GROUP), '')                                AS CUSTBODY_BM_FLD_TRAN_GROUP,
        NULLIF(TRIM(CUSTBODY_BM_IS_COPY_MODE), '')                                  AS CUSTBODY_BM_IS_COPY_MODE,
        NULLIF(TRIM(CUSTBODY_BM_PERIOD_RANGE), '')                                  AS CUSTBODY_BM_PERIOD_RANGE,
        NULLIF(TRIM(CUSTBODY_BM_ROLLOVER_BUDGET), '')                               AS CUSTBODY_BM_ROLLOVER_BUDGET,
        NULLIF(TRIM(CUSTBODY_BM_TRANFLD_VERSION_SEQ), '')                           AS CUSTBODY_BM_TRANFLD_VERSION_SEQ,
        NULLIF(TRIM(CUSTBODY_BM_VERSION), '')                                       AS CUSTBODY_BM_VERSION,
        NULLIF(TRIM(CUSTBODY_BM_VERSION_NOTE), '')                                  AS CUSTBODY_BM_VERSION_NOTE,
        CUSTBODY_CHECKBOX_1                                                         AS CUSTBODY_CHECKBOX_1,
        CAST(CUSTBODY_COMMPCT AS NUMBER(38,6))                                      AS CUSTBODY_COMMPCT,
        CAST(CUSTBODY_CP AS NUMBER(38,0))                                           AS CUSTBODY_CP,
        NULLIF(TRIM(CUSTBODY_CR_CASH_SALE_IF), '')                                  AS CUSTBODY_CR_CASH_SALE_IF,
        CAST(CUSTBODY_CSEG_VENDORTYPE AS NUMBER(38,0))                              AS CUSTBODY_CSEG_VENDORTYPE,
        NULLIF(TRIM(CUSTBODY_CSEGCSEGCUSTSEG_CUS), '')                              AS CUSTBODY_CSEGCSEGCUSTSEG_CUS,
        CAST(CUSTBODY_CSEGCUSTSEG_CHANNEL AS NUMBER(38,0))                          AS CUSTBODY_CSEGCUSTSEG_CHANNEL,
        NULLIF(TRIM(CUSTBODY_CUSTOMER_1), '')                                       AS CUSTBODY_CUSTOMER_1,
        CAST(CUSTBODY_ERSD_DISTRIBUTEDFROMTRX AS NUMBER(38,0))                      AS CUSTBODY_ERSD_DISTRIBUTEDFROMTRX,
        CAST(CUSTBODY_ERSD_REVFROMICJREFE AS NUMBER(38,0))                          AS CUSTBODY_ERSD_REVFROMICJREFE,
        CAST(CUSTBODY_ERSD_VIRDISTREFERENCE AS NUMBER(38,0))                        AS CUSTBODY_ERSD_VIRDISTREFERENCE,
        NULLIF(TRIM(CUSTBODY_FINANCIAL_YEAR_VALUE), '')                             AS CUSTBODY_FINANCIAL_YEAR_VALUE,
        NULLIF(TRIM(CUSTBODY_FIXEDASSET_ASSET), '')                                 AS CUSTBODY_FIXEDASSET_ASSET,
        NULLIF(TRIM(CUSTBODY_FIXEDASSET_SOURCE_TXN), '')                            AS CUSTBODY_FIXEDASSET_SOURCE_TXN,
        CUSTBODY_G_RF_REQ_SEN_EX_APPROVAL                                           AS CUSTBODY_G_RF_REQ_SEN_EX_APPROVAL,
        NULLIF(TRIM(CUSTBODY_LOADING_ICON), '')                                     AS CUSTBODY_LOADING_ICON,
        NULLIF(TRIM(CUSTBODY_NSTS_WODM_CREDIT_MEMO_TYPE), '')                       AS CUSTBODY_NSTS_WODM_CREDIT_MEMO_TYPE,
        CUSTBODY_NSTS_WODM_DEDUCT_MGMT                                              AS CUSTBODY_NSTS_WODM_DEDUCT_MGMT,
        NULLIF(TRIM(CUSTBODY_NSTS_WODM_DEDUCT_MNGMT_ID), '')                        AS CUSTBODY_NSTS_WODM_DEDUCT_MNGMT_ID,
        CUSTBODY_NSTS_WODM_IS_CHARGEBACK                                            AS CUSTBODY_NSTS_WODM_IS_CHARGEBACK,
        CUSTBODY_NSTS_WODM_ON_HOLD                                                  AS CUSTBODY_NSTS_WODM_ON_HOLD,
        NULLIF(TRIM(CUSTBODY_NSTS_WODM_WRITE_OFF_LIMIT), '')                        AS CUSTBODY_NSTS_WODM_WRITE_OFF_LIMIT,
        CUSTBODY_PROMISEDATE                                                        AS CUSTBODY_PROMISEDATE,
        CAST(CUSTBODY_REASONFORRETURN AS NUMBER(38,0))                              AS CUSTBODY_REASONFORRETURN,
        NULLIF(TRIM(CUSTBODY_REF), '')                                              AS CUSTBODY_REF,
        NULLIF(TRIM(CUSTBODY_TEXT_1), '')                                           AS CUSTBODY_TEXT_1,
        CAST(CUSTBODY_VID_DEFAULT_DIST_TMPLT AS NUMBER(38,0))                       AS CUSTBODY_VID_DEFAULT_DIST_TMPLT,
        CUSTBODY_VID_DISABLE_LINE_RULE                                              AS CUSTBODY_VID_DISABLE_LINE_RULE,
        NULLIF(TRIM(CUSTBODY_VID_DIST_REL_JRNL), '')                                AS CUSTBODY_VID_DIST_REL_JRNL,
        CAST(CUSTBODY_VID_DISTRIBUTION_STATUS AS NUMBER(38,0))                      AS CUSTBODY_VID_DISTRIBUTION_STATUS,
        NULLIF(TRIM(CUSTBODY_VID_EXPENSE_JSON), '')                                 AS CUSTBODY_VID_EXPENSE_JSON,
        NULLIF(TRIM(CUSTBODY_VID_EXPENSE_QUICKRULE_JSON), '')                       AS CUSTBODY_VID_EXPENSE_QUICKRULE_JSON,
        NULLIF(TRIM(CUSTBODY_VID_ITEM_JSON), '')                                    AS CUSTBODY_VID_ITEM_JSON,
        NULLIF(TRIM(CUSTBODY_VID_ITEM_QUICKRULE_JSON), '')                          AS CUSTBODY_VID_ITEM_QUICKRULE_JSON,
        NULLIF(TRIM(CUSTBODY_VID_JOURNAL_ERROR), '')                                AS CUSTBODY_VID_JOURNAL_ERROR,
        NULLIF(TRIM(CUSTBODY_VID_LINE_JSON), '')                                    AS CUSTBODY_VID_LINE_JSON,
        NULLIF(TRIM(CUSTBODY_VID_LINE_QUICKRULE_JSON), '')                          AS CUSTBODY_VID_LINE_QUICKRULE_JSON,
        NULLIF(TRIM(CUSTBODY_VID_PROCESSING_SCRIPT), '')                            AS CUSTBODY_VID_PROCESSING_SCRIPT,
        CAST(CUSTBODY_VID_RATE_TYPE AS NUMBER(38,0))                                AS CUSTBODY_VID_RATE_TYPE,
        CAST(CUSTBODY_VID_RELATED_BILL AS NUMBER(38,0))                             AS CUSTBODY_VID_RELATED_BILL,
        CAST(CUSTBODY_VID_TEMPLATE_TYPE AS NUMBER(38,0))                            AS CUSTBODY_VID_TEMPLATE_TYPE,
        NULLIF(TRIM(CUSTBODY_WRM_CLAIMNUMBER), '')                                  AS CUSTBODY_WRM_CLAIMNUMBER,
        NULLIF(TRIM(CUSTBODY_WRM_REPLACEMENTSO), '')                                AS CUSTBODY_WRM_REPLACEMENTSO,
        NULLIF(TRIM(CUSTBODY_WRM_SO_RETURNAUTHORIZATION), '')                       AS CUSTBODY_WRM_SO_RETURNAUTHORIZATION,
        CUSTBODYFRAUD_APPROVED                                                      AS CUSTBODYFRAUD_APPROVED,
        NULLIF(TRIM(CUSTBODYREQ_FRAUD_REVIEW), '')                                  AS CUSTBODYREQ_FRAUD_REVIEW,
        NULLIF(TRIM(CUSTBODYSTORE), '')                                             AS CUSTBODYSTORE,
        CAST(CUSTOMFORM AS NUMBER(38,0))                                            AS CUSTOM_FORM,
        CAST(CUSTOMTYPE AS NUMBER(38,0))                                            AS CUSTOM_TYPE,
        CAST(DAYSOPEN AS NUMBER(38,0))                                              AS DAYSOPEN,
        CAST(DAYSOVERDUESEARCH AS NUMBER(38,6))                                     AS DAYSOVERDUESEARCH,
        CAST(DEFERREDREVENUE AS NUMBER(38,0))                                       AS DEFERRED_REVENUE,
        DISCOUNTDATE                                                                AS DISCOUNT_DATE,
        NULLIF(TRIM(DRACCOUNT), '')                                                 AS DRACCOUNT,
        DUEDATE                                                                     AS DUEDATE,
        NULLIF(TRIM(EFFECTIVITYBASEDON), '')                                        AS EFFECTIVITYBASEDON,
        NULLIF(TRIM(EMAIL), '')                                                     AS EMAIL,
        CAST(EMPLOYEE AS NUMBER(38,0))                                              AS EMPLOYEE,
        ENDDATE                                                                     AS END_DATE,
        CAST(ENTITY AS NUMBER(38,0))                                                AS ENTITY,
        CAST(ENTITYSTATUS AS NUMBER(38,0))                                          AS ENTITY_STATUS,
        CAST(ESTGROSSPROFIT AS NUMBER(38,0))                                        AS ESTGROSSPROFIT,
        CAST(ESTGROSSPROFITPERCENT AS NUMBER(38,6))                                 AS ESTGROSSPROFITPERCENT,
        NULLIF(TRIM(ESTIMATEDBUDGET), '')                                           AS ESTIMATED_BUDGET,
        CAST(EXCHANGERATE AS NUMBER(38,6))                                          AS EXCHANGE_RATE,
        EXPECTEDCLOSEDATE                                                           AS EXPECTEDCLOSEDATE,
        NULLIF(TRIM(EXTERNALID), '')                                                AS EXTERNAL_ID,
        NULLIF(TRIM(FAX), '')                                                       AS FAX,
        FIRMED                                                                      AS FIRMED,
        NULLIF(TRIM(FOB), '')                                                       AS FOB,
        CAST(FORECASTTYPE AS NUMBER(38,0))                                          AS FORECAST_TYPE,
        CAST(FOREIGNAMOUNTPAID AS NUMBER(38,0))                                     AS FOREIGN_AMOUNT_PAID,
        CAST(FOREIGNAMOUNTPAIDNOPOST AS NUMBER(38,0))                               AS FOREIGNAMOUNTPAIDNOPOST,
        CAST(FOREIGNAMOUNTUNPAID AS NUMBER(38,0))                                   AS FOREIGNAMOUNTUNPAID,
        CAST(FOREIGNPAYMENTAMOUNTUNUSED AS NUMBER(38,6))                            AS FOREIGN_PAYMENT_AMOUNT_UNUSED,
        CAST(FOREIGNPAYMENTAMOUNTUSED AS NUMBER(38,6))                              AS FOREIGN_PAYMENT_AMOUNT_USED,
        CAST(FOREIGNPAYMENTAMOUNTUSEDNOPOST AS NUMBER(38,6))                        AS FOREIGNPAYMENTAMOUNTUSEDNOPOST,
        CAST(FOREIGNTOTAL AS NUMBER(38,6))                                          AS FOREIGN_TOTAL,
        FORINVOICEGROUPING                                                          AS FORINVOICEGROUPING,
        NULLIF(TRIM(FULFILLMENTTYPE), '')                                           AS FULFILLMENT_TYPE,
        NULLIF(TRIM(FXACCOUNT), '')                                                 AS FX_ACCOUNT,
        CAST(FXALTSALESTOTAL AS NUMBER(38,6))                                       AS FXALTSALESTOTAL,
        TRY_TO_NUMBER(FXNETALTSALESTOTAL, 38, 6)                                    AS FXNETALTSALESTOTAL,
        NULLIF(TRIM(GROUPEDTO), '')                                                 AS GROUPEDTO,
        NULLIF(TRIM(INCOTERM), '')                                                  AS INCOTERM,
        INTERCOADJ                                                                  AS INTERCOADJ,
        CAST(INTERCOSTATUS AS NUMBER(38,0))                                         AS INTERCO_STATUS,
        CAST(INTERCOTRANSACTION AS NUMBER(38,0))                                    AS INTERCO_TRANSACTION,
        ISACTUALPRODENDDATEENTEREDMANUALLY                                          AS ISACTUALPRODENDDATEENTEREDMANUALLY,
        ISACTUALPRODSTARTDATEENTEREDMANUALLY                                        AS ISACTUALPRODSTARTDATEENTEREDMANUALLY,
        TRY_TO_BOOLEAN(ISAOMAUTOMATED)                                              AS IS_AOM_AUTOMATED,
        ISBOOKSPECIFIC                                                              AS ISBOOKSPECIFIC,
        ISBUDGETAPPROVED                                                            AS IS_BUDGET_APPROVED,
        ISFINCHRG                                                                   AS ISFINCHRG,
        ISMULTISHIPTO                                                               AS ISMULTISHIPTO,
        ISREVERSAL                                                                  AS ISREVERSAL,
        ISWIP                                                                       AS IS_WIP,
        CAST(JOB AS NUMBER(38,0))                                                   AS JOB,
        NULLIF(TRIM(JOURNALTYPE), '')                                               AS JOURNAL_TYPE,
        CAST(LASTMODIFIEDBY AS NUMBER(38,0))                                        AS LAST_MODIFIED_BY,
        LASTMODIFIEDDATE                                                            AS LAST_MODIFIED_DATE,
        CAST(LEADSOURCE AS NUMBER(38,0))                                            AS LEADSOURCE,
        NULLIF(TRIM(LINKEDTRACKINGNUMBERLIST), '')                                  AS LINKEDTRACKINGNUMBERLIST,
        CAST(MANUFACTURINGROUTING AS NUMBER(38,0))                                  AS MANUFACTURINGROUTING,
        CAST(MAXIMUMAMOUNT AS NUMBER(38,6))                                         AS MAXIMUM_AMOUNT,
        CAST(MEMDOC AS NUMBER(38,0))                                                AS MEMDOC,
        NULLIF(TRIM(MEMO), '')                                                      AS MEMO,
        MEMORIZED                                                                   AS MEMORIZED,
        MERGEDINTONEWARRANGEMENTS                                                   AS MERGEDINTONEWARRANGEMENTS,
        NULLIF(TRIM(MESSAGE), '')                                                   AS "MESSAGE",
        CAST(MINIMUMAMOUNT AS NUMBER(38,6))                                         AS MINIMUM_AMOUNT,
        NEEDSBILL                                                                   AS NEEDSBILL,
        CAST(NETALTSALESTOTAL AS NUMBER(38,6))                                      AS NETALTSALESTOTAL,
        CAST(NEXTAPPROVER AS NUMBER(38,0))                                          AS NEXT_APPROVER,
        NEXTBILLDATE                                                                AS NEXT_BILL_DATE,
        CAST(NEXUS AS NUMBER(38,0))                                                 AS NEXUS,
        CAST("NUMBER" AS NUMBER(38,0))                                            AS "NUMBER",
        OPENINGBALANCETRANSACTION                                                   AS OPENING_BALANCE_TRANSACTION,
        CAST(OPPORTUNITY AS NUMBER(38,0))                                           AS OPPORTUNITY,
        ORDPICKED                                                                   AS ORDPICKED,
        ORDRECEIVED                                                                 AS ORDRECEIVED,
        NULLIF(TRIM(OTHERREFNUM), '')                                               AS OTHERREFNUM,
        CAST(PARENTEXPENSEALLOC AS NUMBER(38,0))                                    AS PARENTEXPENSEALLOC,
        CAST(PARTNER AS NUMBER(38,0))                                               AS PARTNER,
        PAYMENTHOLD                                                                 AS PAYMENTHOLD,
        CAST(PAYMENTMETHOD AS NUMBER(38,0))                                         AS PAYMENT_METHOD,
        CAST(PAYMENTOPTION AS NUMBER(38,0))                                         AS PAYMENT_OPTION,
        POSTING                                                                     AS POSTING,
        CAST(POSTINGPERIOD AS NUMBER(38,0))                                         AS POSTING_PERIOD,
        PREVDATE                                                                    AS PREVDATE,
        CAST(PRICINGTIERS AS NUMBER(38,0))                                          AS PRICINGTIERS,
        PRINTEDPICKINGTICKET                                                        AS PRINTEDPICKINGTICKET,
        CAST(PROBABILITY AS NUMBER(38,0))                                           AS PROBABILITY,
        TRY_TO_NUMBER(PROJALTSALESAMT, 38, 6)                                       AS PROJALTSALESAMT,
        CAST(PROJECTEDTOTAL AS NUMBER(38,6))                                        AS PROJECTED_TOTAL,
        NULLIF(TRIM(PURCHASEORDERINSTRUCTIONS), '')                                 AS PURCHASEORDERINSTRUCTIONS,
        CAST(RANGEHIGH AS NUMBER(38,0))                                             AS RANGE_HIGH,
        CAST(RANGELOW AS NUMBER(38,0))                                              AS RANGE_LOW,
        CAST(RECOGNIZEDREVENUE AS NUMBER(38,0))                                     AS RECOGNIZEDREVENUE,
        NULLIF(TRIM(RECORDTYPE), '')                                                AS RECORDTYPE,
        TRY_TO_TIMESTAMP_NTZ(RELEASEDDATETIME)                                      AS RELEASED_DATETIME,
        NULLIF(TRIM(REVCOMMITSTATUSDESCR), '')                                      AS REVCOMMITSTATUSDESCR,
        REVCOMMITTINGSTATUS                                                         AS REVCOMMITTINGSTATUS,
        REVENUECOMMITTEDDATE                                                        AS REVENUE_COMMITTED_DATE,
        NULLIF(TRIM(REVENUESTATUSDESCR), '')                                        AS REVENUESTATUSDESCR,
        CAST(REVERSAL AS NUMBER(38,0))                                              AS REVERSAL,
        REVERSALDATE                                                                AS REVERSALDATE,
        REVERSALDEFER                                                               AS REVERSALDEFER,
        NULLIF(TRIM(REVISION), '')                                                  AS REVISION,
        TRY_TO_DATE(REVRECENDDATE)                                                  AS REVREC_END_DATE,
        REVRECONREVCOMMITMENT                                                       AS REVRECONREVCOMMITMENT,
        NULLIF(TRIM(REVRECSCHEDULE), '')                                            AS REVREC_SCHEDULE,
        TRY_TO_DATE(REVRECSTARTDATE)                                                AS REVREC_START_DATE,
        NULLIF(TRIM(SALESREADINESS), '')                                            AS SALESREADINESS,
        NULLIF(TRIM(SCHEDULINGMETHOD), '')                                          AS SCHEDULINGMETHOD,
        NULLIF(TRIM(SHIPCARRIER), '')                                               AS SHIPCARRIER,
        SHIPCOMPLETE                                                                AS SHIP_COMPLETE,
        SHIPDATE                                                                    AS SHIP_DATE,
        CAST(SHIPMETHOD AS NUMBER(38,0))                                            AS SHIP_METHOD,
        CAST(SHIPPINGADDRESS AS NUMBER(38,0))                                       AS SHIPPING_ADDRESS,
        NULLIF(TRIM(SOURCE), '')                                                    AS SOURCE,
        NULLIF(TRIM(SOURCETRANSACTION), '')                                         AS SOURCE_TRANSACTION,
        STARTDATE                                                                   AS START_DATE,
        NULLIF(TRIM(STATUS), '')                                                    AS STATUS,
        CAST(TERMS AS NUMBER(38,0))                                                 AS TERMS,
        NULLIF(TRIM(TITLE), '')                                                     AS TITLE,
        TOBEEMAILED                                                                 AS TOBEEMAILED,
        TOBEFAXED                                                                   AS TOBEFAXED,
        TOBEPRINTED                                                                 AS TOBEPRINTED,
        CAST(TOSUBSIDIARY AS NUMBER(38,0))                                          AS TO_SUBSIDIARY,
        CAST(TOTALCOSTESTIMATE AS NUMBER(38,6))                                     AS TOTAL_COST_ESTIMATE,
        NULLIF(TRIM(TRACKINGNUMBERLIST), '')                                        AS TRACKINGNUMBERLIST,
        TRANDATE                                                                    AS TR_AN_DATE,
        NULLIF(TRIM(TRANDISPLAYNAME), '')                                           AS TR_AN_DISPLAY_NAME,
        NULLIF(TRIM(TRANID), '')                                                    AS TR_AN_ID,
        TRANISVSOEBUNDLE                                                            AS TRANISVSOEBUNDLE,
        NULLIF(TRIM(TRANSACTIONNUMBER), '')                                         AS TRANSACTION_NUMBER,
        CAST(TRANSFERLOCATION AS NUMBER(38,0))                                      AS TRANSFERLOCATION,
        NULLIF(TRIM("TYPE"), '')                                                    AS "TYPE",
        NULLIF(TRIM(TYPEBASEDDOCUMENTNUMBER), '')                                   AS TYPEBASEDDOCUMENTNUMBER,
        USEITEMCOSTASTRANSFERCOST                                                   AS USEITEMCOSTASTRANSFERCOST,
        USEREVENUEARRANGEMENT                                                       AS USEREVENUEARRANGEMENT,
        VISIBLETOCUSTOMER                                                           AS VISIBLETOCUSTOMER,
        VOID                                                                        AS VOID,
        VOIDED                                                                      AS VOIDED,
        CAST(WEBSITE AS NUMBER(38,0))                                               AS WEBSITE,
        CAST(WEIGHTEDTOTAL AS NUMBER(38,6))                                         AS WEIGHTEDTOTAL,
        NULLIF(TRIM(WINLOSSREASON), '')                                             AS WINLOSSREASON,
        _FIVETRAN_DELETED                                                           AS FIVETRAN_DELETED,
        _FIVETRAN_SYNCED                                                            AS FIVETRAN_SYNCED

    FROM source

),

final AS (

    SELECT
        renamed.*,

        -- Audit metadata
        {% if is_incremental() %}
        COALESCE(
            (SELECT MIN(existing.SILVER_CREATED_ON_TS_UTC)
             FROM {{ this }} existing
             WHERE existing.SURROGATE_KEY = renamed.SURROGATE_KEY),
            CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())
        )                                                                       AS SILVER_CREATED_ON_TS_UTC,
        {% else %}
        CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())                                    AS SILVER_CREATED_ON_TS_UTC,
        {% endif %}
        CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())                                    AS SILVER_UPDATED_ON_TS_UTC,
        CAST(NULL AS TIMESTAMP_NTZ)                               AS SILVER_DELETED_ON_TS_UTC

    FROM renamed

)

SELECT * FROM final
