-- The output have been generated with the assistance of Claude at 2026-06-16T10:00:00Z UTC. The content has been verified by the designated engineer.

{{
  config(
    materialized         = 'incremental',
    unique_key           = 'SURROGATE_KEY',
    incremental_strategy = 'merge',
    on_schema_change     = 'fail',
    tags                 = ['silver', 'staging', 'netsuite']
  )
}}

{#
  Model   : stg_ns_transaction_line
  Layer   : staging
  Grain   : 1 row per STG_NS_TRANSACTION_LINE
  Schema  : static (explicit column list from Silver LLD)
  Cleaning: inline (TransformationRule expressions from Silver LLD)
  Source  : {{ source('ns', 'TRANSACTIONLINE') }}
  Watermark: _FIVETRAN_SYNCED
#}

WITH source AS (

    SELECT *
    FROM {{ source('ns', 'TRANSACTIONLINE') }}
    {% if is_incremental() %}
    WHERE _FIVETRAN_SYNCED > (SELECT MAX(SILVER_UPDATED_ON_TS_UTC) FROM {{ this }})
    {% endif %}

),

renamed AS (

    SELECT
        MD5(CAST(TRANSACTION AS VARCHAR) || '|' || CAST(ID AS VARCHAR))             AS SURROGATE_KEY,
        CAST("TRANSACTION" AS NUMBER(38,0))                                         AS TRANSACTION,
        CAST(ID AS NUMBER(38,0))                                                    AS ID,
        NULLIF(TRIM(ACCOUNTINGLINETYPE), '')                                        AS ACCOUNTING_LINE_TYPE,
        ACTUALSHIPDATE                                                              AS ACTUAL_SHIP_DATE,
        CAST(ALTSALESAMT AS NUMBER(38,6))                                           AS ALTSALESAMT,
        AMORTIZATIONENDDATE                                                         AS AMORTIZATION_END_DATE,
        NULLIF(TRIM(AMORTIZATIONRESIDUAL), '')                                      AS AMORTIZATION_RESIDUAL,
        CAST(AMORTIZATIONSCHED AS NUMBER(38,0))                                     AS AMORTIZATIONSCHED,
        AMORTIZSTARTDATE                                                            AS AMORTIZSTARTDATE,
        CAST(AMOUNTPENDING AS NUMBER(38,6))                                         AS AMOUNT_PENDING,
        ASSEMBLYCOMPONENT                                                           AS ASSEMBLY_COMPONENT,
        TRY_TO_DATE(BILLEDDATE)                                                     AS BILLED_DATE,
        CAST(BILLINGSCHEDULE AS NUMBER(38,0))                                       AS BILLING_SCHEDULE,
        CAST(BILLINGSUBSIDIARY AS NUMBER(38,0))                                     AS BILLING_SUBSIDIARY,
        NULLIF(TRIM(BILLVARIANCESTATUS), '')                                        AS BILL_VARIANCE_STATUS,
        BLANDEDCOST                                                                 AS BLANDEDCOST,
        TRY_TO_NUMBER(BOMQUANTITY, 38, 6)                                           AS BOM_QUANTITY,
        NULLIF(TRIM(BUILDVARIANCE), '')                                             AS BUILD_VARIANCE,
        NULLIF(TRIM(CATCHUPPERIOD), '')                                             AS CATCHUPPERIOD,
        CAST(CATEGORY AS NUMBER(38,0))                                              AS CATEGORY,
        NULLIF(TRIM(CHARGETYPE), '')                                                AS CHARGETYPE,
        CAST(CLASS AS NUMBER(38,0))                                                 AS CLASS,
        CLEARED                                                                     AS CLEARED,
        CLEAREDDATE                                                                 AS CLEAREDDATE,
        CLOSEDATE                                                                   AS CLOSEDATE,
        CAST(COMMITINVENTORY AS NUMBER(38,0))                                       AS COMMITINVENTORY,
        COMMITMENTFIRM                                                              AS COMMITMENTFIRM,
        NULLIF(TRIM(COMPONENTYIELD), '')                                            AS COMPONENT_YIELD,
        CAST(COSTESTIMATE AS NUMBER(38,6))                                          AS COST_ESTIMATE,
        CAST(COSTESTIMATEBASE AS NUMBER(38,6))                                      AS COST_ESTIMATE_BASE,
        CAST(COSTESTIMATERATE AS NUMBER(38,6))                                      AS COST_ESTIMATE_RATE,
        NULLIF(TRIM(COSTESTIMATETYPE), '')                                          AS COST_ESTIMATE_TYPE,
        CAST(CREATEDFROM AS NUMBER(38,0))                                           AS CREATED_FROM,
        CAST(CREATEDPO AS NUMBER(38,0))                                             AS CREATED_PO,
        CAST(CREDITFOREIGNAMOUNT AS NUMBER(38,6))                                   AS CREDIT_FOREIGN_AMOUNT,
        CAST(CUSTCOL10 AS NUMBER(38,0))                                             AS CUSTCOL10,
        NULLIF(TRIM(CUSTCOL11), '')                                                 AS CUSTCOL11,
        CAST(CUSTCOL12 AS NUMBER(38,0))                                             AS CUSTCOL12,
        CAST(CUSTCOL13 AS NUMBER(38,0))                                             AS CUSTCOL13,
        NULLIF(TRIM(CUSTCOL15), '')                                                 AS CUSTCOL15,
        NULLIF(TRIM(CUSTCOL16), '')                                                 AS CUSTCOL16,
        NULLIF(TRIM(CUSTCOL17), '')                                                 AS CUSTCOL17,
        NULLIF(TRIM(CUSTCOL18), '')                                                 AS CUSTCOL18,
        NULLIF(TRIM(CUSTCOL19), '')                                                 AS CUSTCOL19,
        CAST(CUSTCOL3 AS NUMBER(38,0))                                              AS CUSTCOL3,
        CAST(CUSTCOL4 AS NUMBER(38,0))                                              AS CUSTCOL4,
        NULLIF(TRIM(CUSTCOL5), '')                                                  AS CUSTCOL5,
        NULLIF(TRIM(CUSTCOL6), '')                                                  AS CUSTCOL6,
        CAST(CUSTCOL9 AS NUMBER(38,0))                                              AS CUSTCOL9,
        TRY_TO_NUMBER(CUSTCOL_ACC_ANNUALIZED_AMT, 38, 6)                            AS CUSTCOL_ACC_ANNUALIZED_AMT,
        NULLIF(TRIM(CUSTCOL_ACC_BILL_FREQ), '')                                     AS CUSTCOL_ACC_BILL_FREQ,
        NULLIF(TRIM(CUSTCOL_ACC_BILL_SCH_ERROR_MSG), '')                            AS CUSTCOL_ACC_BILL_SCH_ERROR_MSG,
        CAST(CUSTCOL_ACC_ICJE_LINE_APPROVER AS NUMBER(38,0))                        AS CUSTCOL_ACC_ICJE_LINE_APPROVER,
        CAST(CUSTCOL_ACC_ICJE_LINE_PRIMARY_APP AS NUMBER(38,0))                     AS CUSTCOL_ACC_ICJE_LINE_PRIMARY_APP,
        NULLIF(TRIM(CUSTCOL_ACC_LINE_UNIQ_KEY), '')                                 AS CUSTCOL_ACC_LINE_UNIQ_KEY,
        CAST(CUSTCOL_ACC_OPP_NUM_WEEKS AS NUMBER(38,0))                             AS CUSTCOL_ACC_OPP_NUM_WEEKS,
        TRY_TO_NUMBER(CUSTCOL_ACC_OPP_TOTAL_HRS, 38, 6)                             AS CUSTCOL_ACC_OPP_TOTAL_HRS,
        TRY_TO_NUMBER(CUSTCOL_ACC_RAMP_PRO_ANNUAL_AMT, 38, 6)                       AS CUSTCOL_ACC_RAMP_PRO_ANNUAL_AMT,
        TRY_TO_DATE(CUSTCOL_ACC_SERV_END_DATE)                                      AS CUSTCOL_ACC_SERV_END_DATE,
        TRY_TO_DATE(CUSTCOL_ACC_SERV_START_DATE)                                    AS CUSTCOL_ACC_SERV_START_DATE,
        TRY_TO_DATE(CUSTCOL_ACC_TERM_END_DATE)                                      AS CUSTCOL_ACC_TERM_END_DATE,
        NULLIF(TRIM(CUSTCOL_ACC_TERM_IN_MONTHS), '')                                AS CUSTCOL_ACC_TERM_IN_MONTHS,
        TRY_TO_DATE(CUSTCOL_ACC_TERM_START_DATE)                                    AS CUSTCOL_ACC_TERM_START_DATE,
        TRY_TO_NUMBER(CUSTCOL_ACC_YEAR_1_AMT, 38, 6)                                AS CUSTCOL_ACC_YEAR_1_AMT,
        TRY_TO_NUMBER(CUSTCOL_ACC_YEAR_2_AMT, 38, 6)                                AS CUSTCOL_ACC_YEAR_2_AMT,
        TRY_TO_NUMBER(CUSTCOL_ACC_YEAR_3_AMT, 38, 6)                                AS CUSTCOL_ACC_YEAR_3_AMT,
        TRY_TO_NUMBER(CUSTCOL_ACC_YEAR_4_AMT, 38, 6)                                AS CUSTCOL_ACC_YEAR_4_AMT,
        TRY_TO_NUMBER(CUSTCOL_ACC_YEAR_5_AMT, 38, 6)                                AS CUSTCOL_ACC_YEAR_5_AMT,
        TRY_TO_NUMBER(CUSTCOL_ACC_YEAR_6_AMT, 38, 6)                                AS CUSTCOL_ACC_YEAR_6_AMT,
        TRY_TO_NUMBER(CUSTCOL_ACC_YEAR_7_AMT, 38, 6)                                AS CUSTCOL_ACC_YEAR_7_AMT,
        TRY_TO_NUMBER(CUSTCOL_ACC_YEAR_8_AMT, 38, 6)                                AS CUSTCOL_ACC_YEAR_8_AMT,
        CAST(CUSTCOL_ACCL_ICJE_LINE_SECOND_APP AS NUMBER(38,0))                     AS CUSTCOL_ACCL_ICJE_LINE_SECOND_APP,
        NULLIF(TRIM(CUSTCOL_AP_TRANS_DR), '')                                       AS CUSTCOL_AP_TRANS_DR,
        NULLIF(TRIM(CUSTCOL_AP_TRANS_MULT), '')                                     AS CUSTCOL_AP_TRANS_MULT,
        NULLIF(TRIM(CUSTCOL_BM_BUDGET_CTRL_LINK), '')                               AS CUSTCOL_BM_BUDGET_CTRL_LINK,
        TRY_TO_NUMBER(CUSTCOL_BM_BUDGETAMOUNT, 38, 6)                               AS CUSTCOL_BM_BUDGETAMOUNT,
        TRY_TO_NUMBER(CUSTCOL_BM_BUDGETAMOUNTCONSUMED, 38, 6)                       AS CUSTCOL_BM_BUDGETAMOUNTCONSUMED,
        NULLIF(TRIM(CUSTCOL_BM_BUDGETWARNING), '')                                  AS CUSTCOL_BM_BUDGETWARNING,
        NULLIF(TRIM(CUSTCOL_BM_CUSTOMER), '')                                       AS CUSTCOL_BM_CUSTOMER,
        TRY_TO_DATE(CUSTCOL_BM_END_DATE)                                            AS CUSTCOL_BM_END_DATE,
        CAST(CUSTCOL_BM_ITEMACCOUNT AS NUMBER(38,0))                                AS CUSTCOL_BM_ITEMACCOUNT,
        NULLIF(TRIM(CUSTCOL_BM_LINE_BDG_PERIOD), '')                                AS CUSTCOL_BM_LINE_BDG_PERIOD,
        NULLIF(TRIM(CUSTCOL_BM_LINE_BDG_PRD_ID), '')                                AS CUSTCOL_BM_LINE_BDG_PRD_ID,
        NULLIF(TRIM(CUSTCOL_BM_LINE_BDG_VAL), '')                                   AS CUSTCOL_BM_LINE_BDG_VAL,
        TRY_TO_DATE(CUSTCOL_BM_START_DATE)                                          AS CUSTCOL_BM_START_DATE,
        CAST(CUSTCOL_CSEG_VENDORTYPE AS NUMBER(38,0))                               AS CUSTCOL_CSEG_VENDORTYPE,
        NULLIF(TRIM(CUSTCOL_CSEGCSEGCUSTSEG_CUS), '')                               AS CUSTCOL_CSEGCSEGCUSTSEG_CUS,
        CAST(CUSTCOL_CSEGCUSTSEG_CHANNEL AS NUMBER(38,0))                           AS CUSTCOL_CSEGCUSTSEG_CHANNEL,
        NULLIF(TRIM(CUSTCOL_DELETEME), '')                                          AS CUSTCOL_DELETEME,
        NULLIF(TRIM(CUSTCOL_ERSSINGLESUBDISTCUSTOMER), '')                          AS CUSTCOL_ERSSINGLESUBDISTCUSTOMER,
        NULLIF(TRIM(CUSTCOL_ERSSINGLESUBDISTICJ), '')                               AS CUSTCOL_ERSSINGLESUBDISTICJ,
        NULLIF(TRIM(CUSTCOL_ERSSINGLESUBDISTVENDOR), '')                            AS CUSTCOL_ERSSINGLESUBDISTVENDOR,
        NULLIF(TRIM(CUSTCOL_ERSSINGLESUBREVERSEDISTICJ), '')                        AS CUSTCOL_ERSSINGLESUBREVERSEDISTICJ,
        NULLIF(TRIM(CUSTCOL_ERSSINGLSUBDIST), '')                                   AS CUSTCOL_ERSSINGLSUBDIST,
        NULLIF(TRIM(CUSTCOL_FAR_TRN_RELATEDASSET), '')                              AS CUSTCOL_FAR_TRN_RELATEDASSET,
        NULLIF(TRIM(CUSTCOL_FIXEDASSET_ASSETLINE), '')                              AS CUSTCOL_FIXEDASSET_ASSETLINE,
        NULLIF(TRIM(CUSTCOL_GIFTCARDDESIGNCHOOSED), '')                             AS CUSTCOL_GIFTCARDDESIGNCHOOSED,
        NULLIF(TRIM(CUSTCOL_GIFTCARDSENDBYMAIL), '')                                AS CUSTCOL_GIFTCARDSENDBYMAIL,
        NULLIF(TRIM(CUSTCOL_HELMETSIZE), '')                                        AS CUSTCOL_HELMETSIZE,
        NULLIF(TRIM(CUSTCOL_REV_RETURN_FLAG), '')                                   AS CUSTCOL_REV_RETURN_FLAG,
        NULLIF(TRIM(CUSTCOL_RF_RR_END), '')                                         AS CUSTCOL_RF_RR_END,
        NULLIF(TRIM(CUSTCOL_RF_RR_START), '')                                       AS CUSTCOL_RF_RR_START,
        NULLIF(TRIM(CUSTCOL_TESTTEXTFLD), '')                                       AS CUSTCOL_TESTTEXTFLD,
        NULLIF(TRIM(CUSTCOL_VID_BILL_VIEW_DISTRIBUTION), '')                        AS CUSTCOL_VID_BILL_VIEW_DISTRIBUTION,
        NULLIF(TRIM(CUSTCOL_VID_DISTRIBUTION_TEMPLATE), '')                         AS CUSTCOL_VID_DISTRIBUTION_TEMPLATE,
        CUSTCOL_VID_EXCLUDE_DISTRIBUTION                                            AS CUSTCOL_VID_EXCLUDE_DISTRIBUTION,
        CUSTCOL_VID_QUICK_DISTRIBUTION_RULE                                         AS CUSTCOL_VID_QUICK_DISTRIBUTION_RULE,
        NULLIF(TRIM(CUSTCOL_VID_QUICKRULE_JSON_KEY), '')                            AS CUSTCOL_VID_QUICKRULE_JSON_KEY,
        CUSTCOL_WRM_CLAIMITEM                                                       AS CUSTCOL_WRM_CLAIMITEM,
        NULLIF(TRIM(CUSTCOL_WRM_REG_HID_INVDETAIL), '')                             AS CUSTCOL_WRM_REG_HID_INVDETAIL,
        NULLIF(TRIM(CUSTCOL_WRM_REG_HID_PERIOD), '')                                AS CUSTCOL_WRM_REG_HID_PERIOD,
        CUSTCOL_WRM_REG_HID_REGISTERFLAG                                            AS CUSTCOL_WRM_REG_HID_REGISTERFLAG,
        NULLIF(TRIM(CUSTCOL_WRM_REG_HID_TERMS), '')                                 AS CUSTCOL_WRM_REG_HID_TERMS,
        NULLIF(TRIM(CUSTCOL_WRM_REG_HID_TERMTYPE), '')                              AS CUSTCOL_WRM_REG_HID_TERMTYPE,
        CUSTCOL_WRM_REG_HID_TRACKWARRANTY                                           AS CUSTCOL_WRM_REG_HID_TRACKWARRANTY,
        NULLIF(TRIM(CUSTCOL_WRM_REG_HID_WARRANTYBEGIN), '')                         AS CUSTCOL_WRM_REG_HID_WARRANTYBEGIN,
        NULLIF(TRIM(CUSTCOL_WRM_REG_HID_WARRANTYEXPIRE), '')                        AS CUSTCOL_WRM_REG_HID_WARRANTYEXPIRE,
        NULLIF(TRIM(CUSTCOL_WRM_REG_HID_WARRANTYTERMS), '')                         AS CUSTCOL_WRM_REG_HID_WARRANTYTERMS,
        NULLIF(TRIM(CUSTCOL_WRM_REG_REGISTRATION), '')                              AS CUSTCOL_WRM_REG_REGISTRATION,
        NULLIF(TRIM(CUSTCOL_WRM_REG_WARRANTYEXPIRE), '')                            AS CUSTCOL_WRM_REG_WARRANTYEXPIRE,
        CUSTCOL_WRM_REG_WARRANTYREG                                                 AS CUSTCOL_WRM_REG_WARRANTYREG,
        NULLIF(TRIM(CUSTCOL_WRM_REG_WARRANTYTERMS), '')                             AS CUSTCOL_WRM_REG_WARRANTYTERMS,
        CAST(DEBITFOREIGNAMOUNT AS NUMBER(38,6))                                    AS DEBIT_FOREIGN_AMOUNT,
        DEFERREVREC                                                                 AS DEFERREVREC,
        CAST(DEPARTMENT AS NUMBER(38,0))                                            AS DEPARTMENT,
        CAST(DISPLAYLINE AS NUMBER(38,0))                                           AS DISPLAY_LINE,
        NULLIF(TRIM(DOCUMENTNUMBER), '')                                            AS DOCUMENT_NUMBER,
        DONOTDISPLAYLINE                                                            AS DONOTDISPLAYLINE,
        DONOTPRINTLINE                                                              AS DONOTPRINTLINE,
        DROPSHIP                                                                    AS DROP_SHIP,
        DUEDATE                                                                     AS DUEDATE,
        ELIMINATE                                                                   AS ELIMINATE,
        CAST(ENTITY AS NUMBER(38,0))                                                AS ENTITY,
        CAST(ESTGROSSPROFIT AS NUMBER(38,0))                                        AS ESTGROSSPROFIT,
        CAST(ESTGROSSPROFITPERCENT AS NUMBER(38,6))                                 AS ESTGROSSPROFITPERCENT,
        CAST(ESTIMATEDAMOUNT AS NUMBER(38,6))                                       AS ESTIMATED_AMOUNT,
        EXCLUDEFROMRATEREQUEST                                                      AS EXCLUDEFROMRATEREQUEST,
        EXPECTEDRECEIPTDATE                                                         AS EXPECTEDRECEIPTDATE,
        EXPECTEDSHIPDATE                                                            AS EXPECTEDSHIPDATE,
        CAST(EXPENSEACCOUNT AS NUMBER(38,0))                                        AS EXPENSE_ACCOUNT,
        CAST(FOREIGNAMOUNT AS NUMBER(38,6))                                         AS FOREIGN_AMOUNT,
        CAST(FOREIGNAMOUNTPAID AS NUMBER(38,0))                                     AS FOREIGN_AMOUNT_PAID,
        CAST(FOREIGNAMOUNTPAIDNOPOST AS NUMBER(38,0))                               AS FOREIGNAMOUNTPAIDNOPOST,
        CAST(FOREIGNAMOUNTUNPAID AS NUMBER(38,0))                                   AS FOREIGNAMOUNTUNPAID,
        CAST(FOREIGNPAYMENTAMOUNTUNUSED AS NUMBER(38,6))                            AS FOREIGN_PAYMENT_AMOUNT_UNUSED,
        CAST(FOREIGNPAYMENTAMOUNTUSED AS NUMBER(38,6))                              AS FOREIGN_PAYMENT_AMOUNT_USED,
        TRY_TO_NUMBER(FOREIGNPAYMENTAMOUNTUSEDNOPOST, 38, 6)                        AS FOREIGNPAYMENTAMOUNTUSEDNOPOST,
        FULFILLABLE                                                                 AS FULFILLABLE,
        CAST(FXAMOUNTLINKED AS NUMBER(38,6))                                        AS FX_AMOUNT_LINKED,
        TRY_TO_NUMBER(FXVSOEPRICE, 38, 6)                                           AS FX_VSOE_PRICE,
        HASCOSTLINE                                                                 AS HAS_COST_LINE,
        HASFULFILLABLEITEMS                                                         AS HAS_FULFILLABLE_ITEMS,
        CAST(INVENTORYREPORTINGLOCATION AS NUMBER(38,0))                            AS INVENTORY_REPORTING_LOCATION,
        INVSOEBUNDLE                                                                AS INVSOEBUNDLE,
        ISBILLABLE                                                                  AS IS_BILLABLE,
        ISCLOSED                                                                    AS IS_CLOSED,
        ISCOGS                                                                      AS ISCOGS,
        ISCUSTOMGLLINE                                                              AS IS_CUSTOM_GL_LINE,
        ISFULLYSHIPPED                                                              AS ISFULLYSHIPPED,
        ISFXVARIANCE                                                                AS IS_FX_VARIANCE,
        ISINVENTORYAFFECTING                                                        AS ISINVENTORYAFFECTING,
        ISITEMVALUEADJUSTMENT                                                       AS ISITEMVALUEADJUSTMENT,
        ISNONREIMBURSABLE                                                           AS ISNONREIMBURSABLE,
        ISREVRECTRANSACTION                                                         AS IS_REVREC_TRANSACTION,
        ISSCRAP                                                                     AS IS_SCRAP,
        CAST(ITEM AS NUMBER(38,0))                                                  AS ITEM,
        NULLIF(TRIM(ITEMSOURCE), '')                                                AS ITEM_SOURCE,
        NULLIF(TRIM(ITEMTYPE), '')                                                  AS ITEM_TYPE,
        KITCOMPONENT                                                                AS KIT_COMPONENT,
        CAST(KITMEMBEROF AS NUMBER(38,0))                                           AS KIT_MEMBER_OF,
        NULLIF(TRIM(LANDEDCOSTCATEGORY), '')                                        AS LANDEDCOSTCATEGORY,
        LANDEDCOSTPERLINE                                                           AS LANDEDCOSTPERLINE,
        NULLIF(TRIM(LANDEDCOSTSOURCELINEID), '')                                    AS LANDEDCOSTSOURCELINEID,
        LINECREATEDDATE                                                             AS LINE_CREATED_DATE,
        LINELASTMODIFIEDDATE                                                        AS LINE_LAST_MODIFIED_DATE,
        CAST(LINESEQUENCENUMBER AS NUMBER(38,0))                                    AS LINESEQUENCENUMBER,
        CAST(LOCATION AS NUMBER(38,0))                                              AS LOCATION,
        MAINLINE                                                                    AS MAIN_LINE,
        MATCHBILLTORECEIPT                                                          AS MATCH_BILL_TO_RECEIPT,
        NULLIF(TRIM(MEMO), '')                                                      AS MEMO,
        NEEDSREVENUEELEMENT                                                         AS NEEDSREVENUEELEMENT,
        CAST(NETALTSALESAMT AS NUMBER(38,6))                                        AS NETALTSALESAMT,
        CAST(NETAMOUNT AS NUMBER(38,6))                                             AS NET_AMOUNT,
        OLDCOMMITMENTFIRM                                                           AS OLDCOMMITMENTFIRM,
        NULLIF(TRIM(OPERATIONDISPLAYTEXT), '')                                      AS OPERATIONDISPLAYTEXT,
        CAST(ORDERPRIORITY AS NUMBER(38,0))                                         AS ORDERPRIORITY,
        CAST(PAYMENTMETHOD AS NUMBER(38,0))                                         AS PAYMENT_METHOD,
        PERIODCLOSED                                                                AS PERIOD_CLOSED,
        CAST(PORATE AS NUMBER(38,6))                                                AS PO_RATE,
        CAST(PRICE AS NUMBER(38,6))                                                 AS PRICE,
        PROCESSEDBYREVCOMMIT                                                        AS PROCESSEDBYREVCOMMIT,
        NULLIF(TRIM(PROJECTTASK), '')                                               AS PROJECTTASK,
        CAST(QUANTITY AS NUMBER(38,6))                                              AS QUANTITY,
        CAST(QUANTITYBACKORDERED AS NUMBER(38,6))                                   AS QUANTITYBACKORDERED,
        CAST(QUANTITYBILLED AS NUMBER(38,6))                                        AS QUANTITY_BILLED,
        CAST(QUANTITYCOMMITTED AS NUMBER(38,6))                                     AS QUANTITY_COMMITTED,
        CAST(QUANTITYPACKED AS NUMBER(38,6))                                        AS QUANTITYPACKED,
        CAST(QUANTITYPICKED AS NUMBER(38,6))                                        AS QUANTITYPICKED,
        CAST(QUANTITYREJECTED AS NUMBER(38,6))                                      AS QUANTITYREJECTED,
        CAST(QUANTITYREVCOMMITTED AS NUMBER(38,6))                                  AS QUANTITYREVCOMMITTED,
        CAST(QUANTITYSHIPRECV AS NUMBER(38,6))                                      AS QUANTITYSHIPRECV,
        CAST(RATE AS NUMBER(38,6))                                                  AS RATE,
        CAST(RATEAMOUNT AS NUMBER(38,6))                                            AS RATE_AMOUNT,
        CAST(RATEPERCENT AS NUMBER(38,6))                                           AS RATE_PERCENT,
        NULLIF(TRIM(REIMBURSEMENTTYPE), '')                                         AS REIMBURSEMENTTYPE,
        NULLIF(TRIM(REQUESTNOTE), '')                                               AS REQUESTNOTE,
        CAST(REVCOMMITTINGTRANSACTION AS NUMBER(38,0))                              AS REVCOMMITTINGTRANSACTION,
        CAST(REVENUEELEMENT AS NUMBER(38,0))                                        AS REVENUEELEMENT,
        REVRECENDDATE                                                               AS REVREC_END_DATE,
        CAST(REVRECSCHEDULE AS NUMBER(38,0))                                        AS REVREC_SCHEDULE,
        REVRECSTARTDATE                                                             AS REVREC_START_DATE,
        CAST(REVRECTERMINMONTHS AS NUMBER(38,0))                                    AS REVRECTERMINMONTHS,
        CAST(SETTLEMENTAMOUNT AS NUMBER(38,6))                                      AS SETTLEMENTAMOUNT,
        CAST(SHIPMETHOD AS NUMBER(38,0))                                            AS SHIP_METHOD,
        NULLIF(TRIM(SOURCEREVENUEPLAN), '')                                         AS SOURCE_REVENUE_PLAN,
        SPECIALORDER                                                                AS SPECIAL_ORDER,
        CAST(SUBSIDIARY AS NUMBER(38,0))                                            AS SUBSIDIARY,
        CAST(TAXCODE AS NUMBER(38,6))                                               AS TAX_CODE,
        TAXLINE                                                                     AS TAX_LINE,
        NULLIF(TRIM(TAXTYPE), '')                                                   AS TAX_TYPE,
        TRANSACTIONDISCOUNT                                                         AS TRANSACTION_DISCOUNT,
        NULLIF(TRIM(TRANSACTIONLINETYPE), '')                                       AS TRANSACTION_LINE_TYPE,
        CAST(TRANSFERORDERITEMLINEID AS NUMBER(38,0))                               AS TRANSFERORDERITEMLINEID,
        CAST(UNIQUEKEY AS NUMBER(38,0))                                             AS UNIQUEKEY,
        TRY_TO_NUMBER(UNITCOSTOVERRIDE, 38, 6)                                      AS UNIT_COST_OVERRIDE,
        NULLIF(TRIM(UNITCOSTOVERRIDECURRENCY), '')                                  AS UNIT_COST_OVERRIDE_CURRENCY,
        CAST(UNITS AS NUMBER(38,0))                                                 AS UNITS,
        VSOEDELIVERED                                                               AS VSOE_DELIVERED,
        NULLIF(TRIM(VSOEISESTIMATE), '')                                            AS VSOE_IS_ESTIMATE,
        NULLIF(TRIM(VSOEPERMITDISCOUNT), '')                                        AS VSOEPERMITDISCOUNT,
        TRY_TO_NUMBER(VSOEPRICE, 38, 6)                                             AS VSOE_PRICE,
        NULLIF(TRIM(VSOESOPGROUP), '')                                              AS VSOESOPGROUP,
        _FIVETRAN_SYNCED                                                            AS FIVETRAN_SYNCED

    FROM source

),

final AS (

    SELECT
        renamed.*,

        -- Audit metadata
        {% if is_incremental() %}
        COALESCE(
            (SELECT MIN(existing.SILVER_CREATED_ON_TS_UTC)
             FROM {{ this }} existing
             WHERE existing.SURROGATE_KEY = renamed.SURROGATE_KEY),
            CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())
        )                                                                       AS SILVER_CREATED_ON_TS_UTC,
        {% else %}
        CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())                                    AS SILVER_CREATED_ON_TS_UTC,
        {% endif %}
        CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())                                    AS SILVER_UPDATED_ON_TS_UTC,
        CAST(NULL AS TIMESTAMP_NTZ)                               AS SILVER_DELETED_ON_TS_UTC

    FROM renamed

)

SELECT * FROM final
